"""empty message

Revision ID: 0012d82c8099
Revises: c885a4ea6a79
Create Date: 2020-04-14 13:26:41.668501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0012d82c8099'
down_revision = 'c885a4ea6a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_class_subject_books', sa.Column('is_archived', sa.String(length=1), nullable=True))
    op.drop_column('board_class_subject_books', 'is_archieved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_class_subject_books', sa.Column('is_archieved', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.drop_column('board_class_subject_books', 'is_archived')
    # ### end Alembic commands ###
