"""empty message

Revision ID: 00898a9e555c
Revises: 
Create Date: 2020-07-18 11:37:50.522070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00898a9e555c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_detail',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.Column('days_name', sa.String(length=20), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.drop_table('communication_detail')
    op.drop_table('communication_transaction')
    op.alter_column('live_class', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('live_class', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('student_profile', 'points')
    op.drop_column('student_profile', 'is_archived')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('student_profile', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('live_class', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('live_class', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('communication_transaction',
    sa.Column('comm_tran_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comm_id'], ['communication_detail.comm_id'], name='communication_transaction_comm_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name='communication_transaction_student_id_fkey'),
    sa.PrimaryKeyConstraint('comm_tran_id', name='communication_transaction_pkey')
    )
    op.create_table('communication_detail',
    sa.Column('comm_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='communication_detail_school_id_fkey'),
    sa.ForeignKeyConstraint(['status'], ['message_detail.msg_id'], name='communication_detail_status_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], name='communication_detail_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('comm_id', name='communication_detail_pkey')
    )
    op.drop_table('schedule_detail')
    # ### end Alembic commands ###
