"""empty message

Revision ID: 0363abf4efff
Revises: 
Create Date: 2020-06-09 18:29:31.718451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0363abf4efff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_detail', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'content_detail', 'school_profile', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_detail', type_='foreignkey')
    op.drop_column('content_detail', 'school_id')
    # ### end Alembic commands ###
