"""empty message

Revision ID: 04181fe1e019
Revises: dd1db09c23b6
Create Date: 2020-08-19 18:14:14.783557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04181fe1e019'
down_revision = 'dd1db09c23b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transaction', sa.Column('amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transaction', 'amount')
    # ### end Alembic commands ###
