"""empty message

Revision ID: 04253ec81309
Revises: 3d27f281012e
Create Date: 2020-02-25 00:08:41.782918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04253ec81309'
down_revision = '3d27f281012e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profile', sa.Column('impact_school_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_profile', 'impact_school_id')
    # ### end Alembic commands ###
