"""empty message

Revision ID: 072366d2539a
Revises: 07346ef0d52a
Create Date: 2020-04-16 15:49:00.253943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072366d2539a'
down_revision = '07346ef0d52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_detail',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('survey_name', sa.String(length=200), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.PrimaryKeyConstraint('survey_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_detail')
    # ### end Alembic commands ###
