"""empty message

Revision ID: 07346ef0d52a
Revises: 0012d82c8099
Create Date: 2020-04-15 23:02:46.402300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07346ef0d52a'
down_revision = '0012d82c8099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_remarks',
    sa.Column('remark_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('remark_desc', sa.String(length=200), nullable=False),
    sa.Column('remark_type', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['remark_type'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.PrimaryKeyConstraint('remark_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_remarks')
    # ### end Alembic commands ###
