"""empty message

Revision ID: 07aab7a9d5d1
Revises: 76951def1107
Create Date: 2020-08-13 14:44:55.583339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07aab7a9d5d1'
down_revision = '76951def1107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=False),
    sa.Column('comment_type', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_type'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('course_batch',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('batch_start_date', sa.DateTime(), nullable=True),
    sa.Column('batch_end_date', sa.DateTime(), nullable=True),
    sa.Column('batch_start_time', sa.String(length=16), nullable=True),
    sa.Column('batch_end_time', sa.String(length=16), nullable=True),
    sa.Column('days_of_week', sa.String(length=50), nullable=True),
    sa.Column('student_limit', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_detail.course_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('course_review',
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_detail.course_id'], ),
    sa.PrimaryKeyConstraint('cr_id')
    )
    op.create_table('course_topics',
    sa.Column('ct_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_detail.course_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], ),
    sa.PrimaryKeyConstraint('ct_id')
    )
    op.create_table('topic_notes',
    sa.Column('tn_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('notes_name', sa.String(length=100), nullable=True),
    sa.Column('notes_url', sa.String(length=200), nullable=True),
    sa.Column('notes_type', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_detail.course_id'], ),
    sa.ForeignKeyConstraint(['notes_type'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], ),
    sa.PrimaryKeyConstraint('tn_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_notes')
    op.drop_table('course_topics')
    op.drop_table('course_review')
    op.drop_table('course_batch')
    op.drop_table('comments')
    # ### end Alembic commands ###
