"""empty message

Revision ID: 09db130ef92a
Revises: 7ae8fd943671
Create Date: 2020-05-03 10:32:50.316441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09db130ef92a'
down_revision = '7ae8fd943671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_detail', sa.Column('school_id', sa.Integer(), nullable=False))
    op.add_column('inventory_detail', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_detail', 'school_profile', ['school_id'], ['school_id'])
    op.create_foreign_key(None, 'inventory_detail', 'teacher_profile', ['teacher_id'], ['teacher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_detail', type_='foreignkey')
    op.drop_constraint(None, 'inventory_detail', type_='foreignkey')
    op.drop_column('inventory_detail', 'teacher_id')
    op.drop_column('inventory_detail', 'school_id')
    # ### end Alembic commands ###
