"""empty message

Revision ID: 0ce1237d81a6
Revises: d6625d2b2eb9
Create Date: 2019-06-27 15:09:44.151863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce1237d81a6'
down_revision = 'd6625d2b2eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardian_profile', sa.Column('phone', sa.String(length=12), nullable=True))
    op.add_column('student_profile', sa.Column('phone', sa.String(length=12), nullable=True))
    op.add_column('teacher_profile', sa.Column('phone', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profile', 'phone')
    op.drop_column('student_profile', 'phone')
    op.drop_column('guardian_profile', 'phone')
    # ### end Alembic commands ###
