"""empty message

Revision ID: 0ef9066ee29b
Revises: 7031adf33c03
Create Date: 2019-11-03 15:04:23.215567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef9066ee29b'
down_revision = '7031adf33c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('education', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('experience', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('resume', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'resume')
    op.drop_column('user', 'experience')
    op.drop_column('user', 'education')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
