"""empty message

Revision ID: 0fb12d3e467f
Revises: 07081c361c1e
Create Date: 2019-07-27 17:00:58.905546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb12d3e467f'
down_revision = '07081c361c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('reteach_count', sa.Integer(), nullable=True))
    op.drop_constraint('topic_tracker_next_topic_fkey', 'topic_tracker', type_='foreignkey')
    op.drop_column('topic_tracker', 'next_topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('next_topic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('topic_tracker_next_topic_fkey', 'topic_tracker', 'topic_detail', ['next_topic'], ['topic_id'])
    op.drop_column('topic_tracker', 'reteach_count')
    # ### end Alembic commands ###
