"""empty message

Revision ID: 0ff27d85a6da
Revises: a0c409dcc6c6
Create Date: 2019-07-08 23:55:01.688506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff27d85a6da'
down_revision = 'a0c409dcc6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_detail', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_detail', 'school_profile', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_detail', type_='foreignkey')
    op.drop_column('event_detail', 'school_id')
    # ### end Alembic commands ###
