"""empty message

Revision ID: 1511d18870c9
Revises: 
Create Date: 2021-01-12 20:29:10.478545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1511d18870c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('answer_type', sa.Integer(), nullable=True))
    op.add_column('response_capture', sa.Column('question_type', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'response_capture', 'message_detail', ['answer_type'], ['msg_id'])
    op.add_column('session_detail', sa.Column('instructions', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_detail', 'instructions')
    op.drop_constraint(None, 'response_capture', type_='foreignkey')
    op.drop_column('response_capture', 'question_type')
    op.drop_column('response_capture', 'answer_type')
    # ### end Alembic commands ###
