"""empty message

Revision ID: 1737d9d4e34f
Revises: 6e302e0cd4fa
Create Date: 2020-06-07 01:12:04.237668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1737d9d4e34f'
down_revision = '6e302e0cd4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_class',
    sa.Column('live_class_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_val', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('class_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='live_class_school_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], name='live_class_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], name='live_class_teacher_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], name='live_class_topic_id_fkey'),
    sa.PrimaryKeyConstraint('live_class_id', name='live_class_pkey')
    )
    # ### end Alembic commands ###
