"""empty message

Revision ID: 18a97a5e073b
Revises: 6f7567d680d3
Create Date: 2019-07-10 16:35:20.128293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18a97a5e073b'
down_revision = '6f7567d680d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_tracker', 'cover_Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('cover_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
