"""empty message

Revision ID: 18bfe399e3a8
Revises: 8eceacd661c7
Create Date: 2019-06-17 21:59:59.498109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bfe399e3a8'
down_revision = '8eceacd661c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_detail', sa.Column('book_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_detail', 'book_link')
    # ### end Alembic commands ###
