"""empty message

Revision ID: 18db4b6ba609
Revises: 7a47464fec63
Create Date: 2020-02-25 23:21:38.357109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18db4b6ba609'
down_revision = '7a47464fec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_profile', 'impact_school_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profile', sa.Column('impact_school_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
