"""empty message

Revision ID: 1a6724fb370a
Revises: 
Create Date: 2020-07-27 23:26:39.396449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6724fb370a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_detail',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.Column('days_name', sa.String(length=20), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.add_column('response_capture', sa.Column('answer_status', sa.Integer(), nullable=True))
    op.add_column('response_capture', sa.Column('marks_scorec', sa.Integer(), nullable=True))
    op.add_column('session_detail', sa.Column('correct_marks', sa.Integer(), nullable=True))
    op.add_column('session_detail', sa.Column('incorrect_marks', sa.Integer(), nullable=True))
    op.add_column('session_detail', sa.Column('test_time', sa.Integer(), nullable=True))
    op.add_column('session_detail', sa.Column('total_marks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_detail', 'total_marks')
    op.drop_column('session_detail', 'test_time')
    op.drop_column('session_detail', 'incorrect_marks')
    op.drop_column('session_detail', 'correct_marks')
    op.drop_column('response_capture', 'marks_scorec')
    op.drop_column('response_capture', 'answer_status')
    op.drop_table('schedule_detail')
    # ### end Alembic commands ###
