"""empty message

Revision ID: 1b45d10686bf
Revises: 9a117e4d859c
Create Date: 2019-07-15 17:33:57.172303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b45d10686bf'
down_revision = '9a117e4d859c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profile', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'school_profile', 'message_detail', ['board_id'], ['msg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_profile', type_='foreignkey')
    op.drop_column('school_profile', 'board_id')
    # ### end Alembic commands ###
