"""empty message

Revision ID: 1b6541f21abe
Revises: 7023d7cb3414
Create Date: 2019-11-03 00:31:05.480791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6541f21abe'
down_revision = '7023d7cb3414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_detail', sa.Column('posted_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_detail', 'posted_on')
    # ### end Alembic commands ###
