"""empty message

Revision ID: 2131f5e965f2
Revises: 9b7f440b2255
Create Date: 2020-04-10 22:19:46.795419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2131f5e965f2'
down_revision = '9b7f440b2255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_class_subject', sa.Column('is_archieve', sa.String(length=1), nullable=True))
    op.drop_column('board_class_subject', 'is_archived')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_class_subject', sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.drop_column('board_class_subject', 'is_archieve')
    # ### end Alembic commands ###
