"""empty message

Revision ID: 2249213e8358
Revises: 2302f3291ab4
Create Date: 2019-06-21 16:05:43.072074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2249213e8358'
down_revision = '2302f3291ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_details', 'references')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_details', sa.Column('references', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
