"""empty message

Revision ID: 2302f3291ab4
Revises: 4873c6a0a311
Create Date: 2019-06-21 13:02:36.894591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2302f3291ab4'
down_revision = '4873c6a0a311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_options', sa.Column('is_correct', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_options', 'is_correct')
    # ### end Alembic commands ###
