"""empty message

Revision ID: 25c858a3ad15
Revises: c8150ea46b76
Create Date: 2019-12-09 19:56:35.738442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c858a3ad15'
down_revision = 'c8150ea46b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_detail', sa.Column('last_modified_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_detail', 'last_modified_date')
    # ### end Alembic commands ###
