"""empty message

Revision ID: 26f9726c4e4f
Revises: 
Create Date: 2019-07-05 18:38:57.741179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f9726c4e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_details', 'chapter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_details', sa.Column('chapter_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
