"""empty message

Revision ID: 2d97973e436e
Revises: 
Create Date: 2020-06-04 13:54:22.653184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d97973e436e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_detail',
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('homework_name', sa.String(length=200), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.PrimaryKeyConstraint('homework_id')
    )
    op.create_table('homework_questions',
    sa.Column('sq_id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework_detail.homework_id'], ),
    sa.PrimaryKeyConstraint('sq_id')
    )
    op.create_table('inventory_allocation_stud',
    sa.Column('alloc_id', sa.Integer(), nullable=False),
    sa.Column('inv_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Float(), nullable=False),
    sa.Column('allocation_type', sa.String(length=1), nullable=True),
    sa.Column('allocation_status', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_status'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['inv_id'], ['inventory_detail.inv_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('alloc_id')
    )
    op.create_table('student_homework_response',
    sa.Column('homework_response_id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('sq_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework_detail.homework_id'], ),
    sa.ForeignKeyConstraint(['sq_id'], ['homework_questions.sq_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('homework_response_id')
    )
    op.drop_table('teacher_subject')
    op.drop_table('schedule_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_detail',
    sa.Column('slot_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slot_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_sec_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('days_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], name='schedule_detail_class_sec_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='schedule_detail_school_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], name='schedule_detail_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], name='schedule_detail_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('slot_id', name='schedule_detail_pkey')
    )
    op.create_table('teacher_subject',
    sa.Column('teacher_subj_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_val', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='teacher_subject_school_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], name='teacher_subject_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], name='teacher_subject_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('teacher_subj_id', name='teacher_subject_pkey')
    )
    op.drop_table('student_homework_response')
    op.drop_table('inventory_allocation_stud')
    op.drop_table('homework_questions')
    op.drop_table('homework_detail')
    # ### end Alembic commands ###
