"""empty message

Revision ID: 2e54140c14a9
Revises: 9badbddc07ad
Create Date: 2020-08-26 17:14:31.936392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e54140c14a9'
down_revision = '9badbddc07ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_batch', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'course_batch', 'course_detail', ['course_id'], ['course_id'])
    op.add_column('course_enrollment', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'course_enrollment', 'course_detail', ['course_id'], ['course_id'])
    op.add_column('course_review', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'course_review', 'course_detail', ['course_id'], ['course_id'])
    op.add_column('course_topics', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'course_topics', 'course_detail', ['course_id'], ['course_id'])
    op.add_column('topic_notes', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'topic_notes', 'course_detail', ['course_id'], ['course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_notes', type_='foreignkey')
    op.drop_column('topic_notes', 'course_id')
    op.drop_constraint(None, 'course_topics', type_='foreignkey')
    op.drop_column('course_topics', 'course_id')
    op.drop_constraint(None, 'course_review', type_='foreignkey')
    op.drop_column('course_review', 'course_id')
    op.drop_constraint(None, 'course_enrollment', type_='foreignkey')
    op.drop_column('course_enrollment', 'course_id')
    op.drop_constraint(None, 'course_batch', type_='foreignkey')
    op.drop_column('course_batch', 'course_id')
    # ### end Alembic commands ###
