"""empty message

Revision ID: 2e700b29b398
Revises: a8fd4d6d9371
Create Date: 2020-04-16 21:37:53.109975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e700b29b398'
down_revision = 'a8fd4d6d9371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_survey_response',
    sa.Column('survey_response_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('sq_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sq_id'], ['survey_questions.sq_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_detail.survey_id'], ),
    sa.PrimaryKeyConstraint('survey_response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_survey_response')
    # ### end Alembic commands ###
