"""empty message

Revision ID: 2ebec7c8a388
Revises: 7859ce7eab4f
Create Date: 2019-09-14 19:22:45.986910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebec7c8a388'
down_revision = '7859ce7eab4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_profile', sa.Column('device_preference', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher_profile', 'message_detail', ['device_preference'], ['msg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_profile', type_='foreignkey')
    op.drop_column('teacher_profile', 'device_preference')
    # ### end Alembic commands ###
