"""empty message

Revision ID: 30ac849bf430
Revises: 88cdacd07950
Create Date: 2019-06-27 12:39:00.519579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ac849bf430'
down_revision = '88cdacd07950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('student_profile', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('student_profile', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.drop_column('student_profile', 'student_full_name')
    op.drop_column('student_profile', 'student_first_name')
    op.drop_column('student_profile', 'student_last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('student_last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_profile', sa.Column('student_first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_profile', sa.Column('student_full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('student_profile', 'last_name')
    op.drop_column('student_profile', 'full_name')
    op.drop_column('student_profile', 'first_name')
    # ### end Alembic commands ###
