"""empty message

Revision ID: 32b585da72a8
Revises: b32ff402275d
Create Date: 2019-06-18 18:46:38.824912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b585da72a8'
down_revision = 'b32ff402275d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic_tracker', 'school_profile', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_tracker', type_='foreignkey')
    op.drop_column('topic_tracker', 'school_id')
    # ### end Alembic commands ###
