"""empty message

Revision ID: 334e0ff31246
Revises: 66fbb6f2d7d2
Create Date: 2019-09-09 22:08:00.548382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334e0ff31246'
down_revision = '66fbb6f2d7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_details_class_val_fkey', 'test_details', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('test_details_class_val_fkey', 'test_details', 'message_detail', ['class_val'], ['msg_id'])
    # ### end Alembic commands ###
