"""empty message

Revision ID: 3741f01dda93
Revises: 49b466df8a7d
Create Date: 2019-11-02 21:04:25.698217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3741f01dda93'
down_revision = '49b466df8a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profile', sa.Column('how_to_reach', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_profile', 'how_to_reach')
    # ### end Alembic commands ###
