"""empty message

Revision ID: 37bb52d71d71
Revises: d8ffc5199b2f
Create Date: 2020-06-07 03:52:58.235684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bb52d71d71'
down_revision = 'd8ffc5199b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_mapping',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('module_type', sa.Integer(), nullable=True),
    sa.Column('module_url', sa.String(length=200), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_type'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('module_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_mapping')
    # ### end Alembic commands ###
