"""empty message

Revision ID: 43e40abc9de7
Revises: 2e54140c14a9
Create Date: 2020-08-26 17:16:59.976510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e40abc9de7'
down_revision = '2e54140c14a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_test', sa.Column('batch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'batch_test', 'course_batch', ['batch_id'], ['batch_id'])
    op.add_column('course_enrollment', sa.Column('batch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'course_enrollment', 'course_batch', ['batch_id'], ['batch_id'])
    op.add_column('payment_transaction', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_transaction', 'course_batch', ['batch_id'], ['batch_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_transaction', type_='foreignkey')
    op.drop_column('payment_transaction', 'batch_id')
    op.drop_constraint(None, 'course_enrollment', type_='foreignkey')
    op.drop_column('course_enrollment', 'batch_id')
    op.drop_constraint(None, 'batch_test', type_='foreignkey')
    op.drop_column('batch_test', 'batch_id')
    # ### end Alembic commands ###
