"""empty message

Revision ID: 4438f85e30ec
Revises: d25646a61d2e
Create Date: 2020-07-28 20:25:04.729666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4438f85e30ec'
down_revision = 'd25646a61d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_detail', sa.Column('meta_val', sa.String(length=200), nullable=True))
    op.add_column('module_detail', sa.Column('title_val', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_detail', 'title_val')
    op.drop_column('module_detail', 'meta_val')
    # ### end Alembic commands ###
