"""empty message

Revision ID: 471442dc97ee
Revises: 
Create Date: 2019-07-08 23:23:52.594126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '471442dc97ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_detail', sa.Column('event_category', sa.DateTime(), nullable=True))
    op.add_column('event_detail', sa.Column('event_date', sa.DateTime(), nullable=True))
    op.add_column('event_detail', sa.Column('event_duration', sa.String(length=10), nullable=True))
    op.add_column('event_detail', sa.Column('event_end', sa.DateTime(), nullable=True))
    op.add_column('event_detail', sa.Column('event_start', sa.DateTime(), nullable=True))
    op.drop_column('event_detail', 'event_color')
    op.drop_column('event_detail', 'date')
    op.drop_column('event_detail', 'event_duration_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_detail', sa.Column('event_duration_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_detail', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event_detail', sa.Column('event_color', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('event_detail', 'event_start')
    op.drop_column('event_detail', 'event_end')
    op.drop_column('event_detail', 'event_duration')
    op.drop_column('event_detail', 'event_date')
    op.drop_column('event_detail', 'event_category')
    # ### end Alembic commands ###
