"""empty message

Revision ID: 47e2788eb31e
Revises: 
Create Date: 2019-07-15 11:39:45.675962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e2788eb31e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_detail', 'section_semi_annual_rank')
    op.drop_column('performance_detail', 'student_semi_annual_rank')
    op.drop_column('performance_detail', 'student_month_rank')
    op.drop_column('performance_detail', 'school_semi_annual_rank')
    op.drop_column('performance_detail', 'class_year_rank')
    op.drop_column('performance_detail', 'student_year_rank')
    op.drop_column('performance_detail', 'school_month_rank')
    op.drop_column('performance_detail', 'section_year_rank')
    op.drop_column('performance_detail', 'school_year_rank')
    op.add_column('result_upload', sa.Column('total_marks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result_upload', 'total_marks')
    op.add_column('performance_detail', sa.Column('school_year_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_detail', sa.Column('section_year_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_detail', sa.Column('school_month_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_detail', sa.Column('student_year_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_detail', sa.Column('class_year_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_detail', sa.Column('school_semi_annual_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_detail', sa.Column('student_month_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_detail', sa.Column('student_semi_annual_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_detail', sa.Column('section_semi_annual_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
