"""empty message

Revision ID: 4863aa216651
Revises: 2ebec7c8a388
Create Date: 2019-09-14 20:50:49.019762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4863aa216651'
down_revision = '2ebec7c8a388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resp_session_question', sa.Column('resp_session_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resp_session_question', 'resp_session_id')
    # ### end Alembic commands ###
