"""empty message

Revision ID: 493e4bb32500
Revises: afa7cb274c6b
Create Date: 2020-08-22 12:01:24.402657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493e4bb32500'
down_revision = 'afa7cb274c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_detail', sa.Column('difficulty_level', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_detail', 'message_detail', ['difficulty_level'], ['msg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_detail', type_='foreignkey')
    op.drop_column('course_detail', 'difficulty_level')
    # ### end Alembic commands ###
