"""empty message

Revision ID: 49b466df8a7d
Revises: f8bb9cf4860e
Create Date: 2019-11-02 19:31:00.003466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b466df8a7d'
down_revision = 'f8bb9cf4860e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_detail', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('job_detail', sa.Column('fooding', sa.String(length=100), nullable=True))
    op.add_column('job_detail', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('job_detail', sa.Column('stay', sa.String(length=100), nullable=True))
    op.add_column('job_detail', sa.Column('term', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_detail', 'term')
    op.drop_column('job_detail', 'stay')
    op.drop_column('job_detail', 'status')
    op.drop_column('job_detail', 'fooding')
    op.drop_column('job_detail', 'category')
    # ### end Alembic commands ###
