"""empty message

Revision ID: 4d80cf24a792
Revises: 9d5fc8ed7c3a
Create Date: 2019-11-06 16:28:01.050229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d80cf24a792'
down_revision = '9d5fc8ed7c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'willing_to_travel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('willing_to_travel', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
