"""empty message

Revision ID: 4f428e947800
Revises: 2e700b29b398
Create Date: 2020-04-16 21:43:15.463848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f428e947800'
down_revision = '2e700b29b398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_detail', sa.Column('is_archived', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_detail', 'is_archived')
    # ### end Alembic commands ###
