"""create table StudentClassSecDetail

Revision ID: 4feeccfd8f09
Revises: 551036eadee1
Create Date: 2020-03-20 17:42:56.772438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4feeccfd8f09'
down_revision = '551036eadee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_class_sec_detail',
    sa.Column('student_class_sec_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.Column('class_val', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=1), nullable=True),
    sa.Column('is_current', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('student_class_sec_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_class_sec_detail')
    # ### end Alembic commands ###
