"""empty message

Revision ID: 50e334a2955f
Revises: 8aa1d3f9dfca
Create Date: 2019-06-28 19:43:59.427852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e334a2955f'
down_revision = '8aa1d3f9dfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('is_correct', sa.String(length=1), nullable=True))
    op.add_column('response_capture', sa.Column('response_option', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_capture', 'response_option')
    op.drop_column('response_capture', 'is_correct')
    # ### end Alembic commands ###
