"""empty message

Revision ID: 58898dbfe819
Revises: 04181fe1e019
Create Date: 2020-08-21 15:49:54.485691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58898dbfe819'
down_revision = '04181fe1e019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_detail', sa.Column('image_url', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_detail', 'image_url')
    # ### end Alembic commands ###
