"""empty message

Revision ID: 5e89df74da18
Revises: 83ada2e931ca
Create Date: 2019-06-11 18:32:19.960689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e89df74da18'
down_revision = '83ada2e931ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('last_topic', sa.Integer(), nullable=True))
    op.add_column('topic_tracker', sa.Column('next_topic', sa.Integer(), nullable=True))
    op.drop_constraint('topic_tracker_teacher_id_fkey', 'topic_tracker', type_='foreignkey')
    op.drop_constraint('topic_tracker_topic_id_fkey', 'topic_tracker', type_='foreignkey')
    op.drop_constraint('topic_tracker_school_id_fkey', 'topic_tracker', type_='foreignkey')
    op.create_foreign_key(None, 'topic_tracker', 'topic_detail', ['last_topic'], ['topic_id'])
    op.create_foreign_key(None, 'topic_tracker', 'topic_detail', ['next_topic'], ['topic_id'])
    op.drop_column('topic_tracker', 'is_completed')
    op.drop_column('topic_tracker', 'teacher_id')
    op.drop_column('topic_tracker', 'school_id')
    op.drop_column('topic_tracker', 'topic_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('topic_tracker', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('topic_tracker', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('topic_tracker', sa.Column('is_completed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topic_tracker', type_='foreignkey')
    op.drop_constraint(None, 'topic_tracker', type_='foreignkey')
    op.create_foreign_key('topic_tracker_school_id_fkey', 'topic_tracker', 'school_profile', ['school_id'], ['school_id'])
    op.create_foreign_key('topic_tracker_topic_id_fkey', 'topic_tracker', 'topic_detail', ['topic_id'], ['topic_id'])
    op.create_foreign_key('topic_tracker_teacher_id_fkey', 'topic_tracker', 'teacher_profile', ['teacher_id'], ['teacher_id'])
    op.drop_column('topic_tracker', 'next_topic')
    op.drop_column('topic_tracker', 'last_topic')
    # ### end Alembic commands ###
