"""empty message

Revision ID: 5e91aaf4e388
Revises: 967a479e5cf3
Create Date: 2019-10-18 21:49:21.686092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e91aaf4e388'
down_revision = '967a479e5cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_detail',
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('camp_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('archive_status', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('camp_id', 'camp_name')
    )
    op.create_table('invoice_detail',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('sent_to', sa.Integer(), nullable=True),
    sa.Column('sent_email', sa.String(length=200), nullable=True),
    sa.Column('billing_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('subcription_charge', sa.Integer(), nullable=True),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('invoice_total', sa.Integer(), nullable=True),
    sa.Column('invoice_status', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['sent_to'], ['teacher_profile.teacher_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_table('payment_detail',
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('pay_type', sa.Integer(), nullable=True),
    sa.Column('account_card_num', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Integer(), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('ac_holder_name', sa.String(length=100), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('school_admin', sa.Integer(), nullable=True),
    sa.Column('archive_status', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pay_type'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['school_admin'], ['teacher_profile.teacher_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    op.create_table('subscription_detail',
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.String(length=100), nullable=True),
    sa.Column('monthly_charge', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('school_type', sa.Integer(), nullable=True),
    sa.Column('archive_status', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_type'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.drop_table('financial_details')
    op.add_column('school_profile', sa.Column('next_bill_due', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_profile', 'next_bill_due')
    op.create_table('financial_details',
    sa.Column('fin_det_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subscription_amt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maint_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_sec_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], name='financial_details_class_sec_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='financial_details_school_id_fkey'),
    sa.PrimaryKeyConstraint('fin_det_id', name='financial_details_pkey')
    )
    op.drop_table('subscription_detail')
    op.drop_table('payment_detail')
    op.drop_table('invoice_detail')
    op.drop_table('campaign_detail')
    # ### end Alembic commands ###
