"""empty message

Revision ID: 6151dc4f9062
Revises: 334e0ff31246
Create Date: 2019-09-10 00:31:55.937526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6151dc4f9062'
down_revision = '334e0ff31246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result_upload', sa.Column('upload_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result_upload', 'upload_id')
    # ### end Alembic commands ###
