"""empty message

Revision ID: 61d1b0e8821f
Revises: 3741f01dda93
Create Date: 2019-11-02 22:23:57.091353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d1b0e8821f'
down_revision = '3741f01dda93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.drop_constraint('job_application_seeker_id_fkey', 'job_application', type_='foreignkey')
    op.create_foreign_key(None, 'job_application', 'teacher_profile', ['teacher_id'], ['teacher_id'])
    op.drop_column('job_application', 'seeker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('seeker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_application', type_='foreignkey')
    op.create_foreign_key('job_application_seeker_id_fkey', 'job_application', 'teacher_profile', ['seeker_id'], ['teacher_id'])
    op.drop_column('job_application', 'teacher_id')
    # ### end Alembic commands ###
