"""empty message

Revision ID: 626d81d96abe
Revises: 4f428e947800
Create Date: 2020-04-22 20:51:47.128490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626d81d96abe'
down_revision = '4f428e947800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_details', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_details', 'teacher_profile', ['teacher_id'], ['teacher_id'])
    op.add_column('topic_detail', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic_detail', 'teacher_profile', ['teacher_id'], ['teacher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_detail', type_='foreignkey')
    op.drop_column('topic_detail', 'teacher_id')
    op.drop_constraint(None, 'book_details', type_='foreignkey')
    op.drop_column('book_details', 'teacher_id')
    # ### end Alembic commands ###
