"""empty message

Revision ID: 632d402cf847
Revises: 9715b1128b2b
Create Date: 2020-08-24 20:34:25.124020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632d402cf847'
down_revision = '9715b1128b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_detail',
    sa.Column('bd_id', sa.Integer(), nullable=False),
    sa.Column('account_num', sa.String(length=30), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.PrimaryKeyConstraint('bd_id'),
    sa.UniqueConstraint('vendor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_detail')
    # ### end Alembic commands ###
