"""empty message

Revision ID: 6649f9344e41
Revises: 
Create Date: 2020-09-10 21:01:51.911545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6649f9344e41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('student_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'response_capture', 'user', ['student_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response_capture', type_='foreignkey')
    op.drop_column('response_capture', 'student_user_id')
    # ### end Alembic commands ###
