"""empty message

Revision ID: 66fbb6f2d7d2
Revises: 0fb12d3e467f
Create Date: 2019-07-31 17:01:14.489454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66fbb6f2d7d2'
down_revision = '0fb12d3e467f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendance_class_sec_id_fkey', 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'class_sec_id')
    op.drop_constraint('uk_class_sec_id', 'class_section', type_='unique')
    op.add_column('school_profile', sa.Column('school_picture', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_profile', 'school_picture')
    op.create_unique_constraint('uk_class_sec_id', 'class_section', ['class_sec_id'])
    op.add_column('attendance', sa.Column('class_sec_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('attendance_class_sec_id_fkey', 'attendance', 'class_section', ['class_sec_id'], ['class_sec_id'])
    # ### end Alembic commands ###
