"""empty message

Revision ID: 681dcadaf46e
Revises: 4756fe7e2f1d
Create Date: 2019-10-10 15:25:41.510871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681dcadaf46e'
down_revision = '4756fe7e2f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_detail',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('page_link', sa.String(length=200), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('tag_detail',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('tag_type', sa.Integer(), nullable=True),
    sa.Column('archive_status', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_type'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.add_column('student_profile', sa.Column('student_unique_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profile', 'student_unique_id')
    op.drop_table('tag_detail')
    op.drop_table('module_detail')
    # ### end Alembic commands ###
