"""empty message

Revision ID: 6891c4bddaee
Revises: 
Create Date: 2020-06-16 17:32:26.387989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6891c4bddaee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_detail', sa.Column('is_archived', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_detail', 'is_archived')
    # ### end Alembic commands ###
