"""empty message

Revision ID: 68de95e688c2
Revises: 
Create Date: 2020-08-10 13:18:35.908401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68de95e688c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance', 'student_profile', ['student_id'], ['student_id'])
    op.create_foreign_key(None, 'attendance', 'class_section', ['class_sec_id'], ['class_sec_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'student_id')
    op.drop_column('attendance', 'class_sec_id')
    # ### end Alembic commands ###
