"""empty message

Revision ID: 690ad604a50d
Revises: c51643298800
Create Date: 2019-06-28 19:31:18.688639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690ad604a50d'
down_revision = 'c51643298800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_capture', 'is_correct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('is_correct', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
