"""empty message

Revision ID: 6a67dfee6b17
Revises: 1a6724fb370a
Create Date: 2020-07-27 23:29:28.074964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a67dfee6b17'
down_revision = '1a6724fb370a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('marks_scored', sa.Integer(), nullable=True))
    op.drop_column('response_capture', 'marks_scorec')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('marks_scorec', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('response_capture', 'marks_scored')
    # ### end Alembic commands ###
