"""empty message

Revision ID: 6f7567d680d3
Revises: 0ff27d85a6da
Create Date: 2019-07-10 16:24:41.504794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7567d680d3'
down_revision = '0ff27d85a6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('last_modified_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_tracker', 'last_modified_date')
    # ### end Alembic commands ###
