"""empty message

Revision ID: 7023d7cb3414
Revises: 68c057d1d412
Create Date: 2019-11-03 00:02:29.241844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7023d7cb3414'
down_revision = '68c057d1d412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_application', 'status')
    # ### end Alembic commands ###
