"""empty message

Revision ID: 7031adf33c03
Revises: d89013dd8d86
Create Date: 2019-11-03 13:22:17.129392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7031adf33c03'
down_revision = 'd89013dd8d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('applier_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_application', 'user', ['applier_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_application', type_='foreignkey')
    op.drop_column('job_application', 'applier_user_id')
    # ### end Alembic commands ###
