"""empty message

Revision ID: 721d07c44cfa
Revises: 4feeccfd8f09
Create Date: 2020-04-01 12:59:05.319804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721d07c44cfa'
down_revision = '4feeccfd8f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_class_sec_detail', sa.Column('promotion_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_class_sec_detail', 'promotion_date')
    # ### end Alembic commands ###
