"""empty message

Revision ID: 73b08f202a05
Revises: 4d80cf24a792
Create Date: 2019-11-06 16:32:14.387025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b08f202a05'
down_revision = '4d80cf24a792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('willing_to_travel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'willing_to_travel')
    # ### end Alembic commands ###
