"""empty message

Revision ID: 76951def1107
Revises: 
Create Date: 2020-08-13 14:40:43.269660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76951def1107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_detail',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('summary_url', sa.String(length=400), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.String(length=1), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('payment_transaction',
    sa.Column('tran_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('payer_user_id', sa.Integer(), nullable=True),
    sa.Column('payer_name', sa.String(length=100), nullable=True),
    sa.Column('payer_phone', sa.String(length=12), nullable=True),
    sa.Column('payer_email', sa.String(length=50), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('trans_type', sa.Integer(), nullable=False),
    sa.Column('payment_for', sa.Integer(), nullable=False),
    sa.Column('request_sign_hash', sa.String(length=200), nullable=True),
    sa.Column('response_sign_hash', sa.String(length=200), nullable=True),
    sa.Column('response_sign_check', sa.String(length=10), nullable=True),
    sa.Column('tran_status', sa.Integer(), nullable=False),
    sa.Column('gateway_ref_id', sa.String(length=100), nullable=True),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('tran_msg', sa.String(length=50), nullable=True),
    sa.Column('tran_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('anonymous_payer', sa.String(length=1), nullable=True),
    sa.Column('anonymous_amount', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['payer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_for'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.ForeignKeyConstraint(['tran_status'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['trans_type'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('tran_id'),
    sa.UniqueConstraint('order_id')
    )
    op.add_column('live_class', sa.Column('room_id', sa.String(length=300), nullable=True))
    op.add_column('teacher_profile', sa.Column('courses_created', sa.Integer(), nullable=True))
    op.add_column('teacher_profile', sa.Column('hours_taught_online', sa.Integer(), nullable=True))
    op.add_column('teacher_profile', sa.Column('room_id', sa.String(length=300), nullable=True))
    op.add_column('teacher_profile', sa.Column('students_taught', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profile', 'students_taught')
    op.drop_column('teacher_profile', 'room_id')
    op.drop_column('teacher_profile', 'hours_taught_online')
    op.drop_column('teacher_profile', 'courses_created')
    op.drop_column('live_class', 'room_id')
    op.drop_table('payment_transaction')
    op.drop_table('course_detail')
    # ### end Alembic commands ###
