"""empty message

Revision ID: 7859ce7eab4f
Revises: d6e5fa7f39be
Create Date: 2019-09-14 16:39:49.035808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7859ce7eab4f'
down_revision = 'd6e5fa7f39be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_detail', sa.Column('current_question', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_detail', 'question_details', ['current_question'], ['question_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_detail', type_='foreignkey')
    op.drop_column('session_detail', 'current_question')
    # ### end Alembic commands ###
