"""empty message

Revision ID: 7a47464fec63
Revises: 0c06967ef177
Create Date: 2020-02-25 23:02:16.356845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a47464fec63'
down_revision = '0c06967ef177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profile', sa.Column('impact_school_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_profile', 'impact_school_id')
    # ### end Alembic commands ###
