"""create all new tables

Revision ID: 7a830373cac3
Revises: 
Create Date: 2018-06-15 20:15:40.729780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a830373cac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_details',
    sa.Column('art_id', sa.Integer(), nullable=False),
    sa.Column('art_name', sa.String(length=120), nullable=False),
    sa.Column('art_content', sa.String(length=500), nullable=True),
    sa.Column('art_read_count', sa.Integer(), nullable=True),
    sa.Column('art_author', sa.String(length=120), nullable=True),
    sa.Column('art_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('art_id')
    )
    op.create_table('author_details',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.String(length=120), nullable=False),
    sa.Column('auth_art_count', sa.Integer(), nullable=True),
    sa.Column('art_indiv_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('cost_details',
    sa.Column('cost_id', sa.Integer(), nullable=False),
    sa.Column('cost_item', sa.String(length=120), nullable=False),
    sa.Column('cost_unit_price', sa.Integer(), nullable=False),
    sa.Column('cost_center', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cost_id')
    )
    op.create_table('hospital_details',
    sa.Column('hosp_id', sa.Integer(), nullable=False),
    sa.Column('hosp_name', sa.String(length=120), nullable=False),
    sa.Column('hosp_location', sa.String(length=120), nullable=True),
    sa.Column('hosp_phone', sa.Integer(), nullable=True),
    sa.Column('hosp_city', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('hosp_id')
    )
    op.create_table('medicine_details',
    sa.Column('med_id', sa.Integer(), nullable=False),
    sa.Column('med_name', sa.String(length=120), nullable=False),
    sa.Column('med_dosage', sa.String(length=120), nullable=False),
    sa.Column('med_cost_id', sa.Integer(), nullable=True),
    sa.Column('med_in_stock', sa.Integer(), nullable=True),
    sa.Column('med_maker', sa.String(length=120), nullable=True),
    sa.Column('med_cancer_type', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('med_id')
    )
    op.create_table('member_details',
    sa.Column('mem_id', sa.Integer(), nullable=False),
    sa.Column('mem_name', sa.String(length=120), nullable=False),
    sa.Column('mem_location', sa.String(length=120), nullable=True),
    sa.Column('mem_dept', sa.String(length=120), nullable=True),
    sa.Column('mem_age', sa.Integer(), nullable=True),
    sa.Column('mem_type', sa.String(length=2), nullable=True),
    sa.Column('mem_join_dt', sa.DateTime(), nullable=True),
    sa.Column('mem_end_dt', sa.DateTime(), nullable=True),
    sa.Column('mem_gender', sa.String(length=2), nullable=True),
    sa.Column('mem_hour_day', sa.Integer(), nullable=True),
    sa.Column('mem_city', sa.String(length=120), nullable=True),
    sa.Column('mem_branch_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mem_id')
    )
    op.create_table('message_details',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('msg_type', sa.String(length=120), nullable=True),
    sa.Column('msg_description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('survivor_details',
    sa.Column('sur_id', sa.Integer(), nullable=False),
    sa.Column('sur_name', sa.String(length=120), nullable=False),
    sa.Column('sur_email', sa.String(length=120), nullable=False),
    sa.Column('sur_treatment_status', sa.String(length=120), nullable=True),
    sa.Column('sur_address', sa.String(length=500), nullable=True),
    sa.Column('sur_city', sa.Integer(), nullable=True),
    sa.Column('sur_cnsl_prvdr', sa.String(length=2), nullable=True),
    sa.Column('sur_cnsl_require', sa.String(length=2), nullable=True),
    sa.Column('sur_phone', sa.Integer(), nullable=True),
    sa.Column('sur_gender', sa.String(length=2), nullable=True),
    sa.Column('sur_age', sa.Integer(), nullable=True),
    sa.Column('sur_newsletter', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('sur_id')
    )
    op.create_table('transaction_details',
    sa.Column('trn_id', sa.Integer(), nullable=False),
    sa.Column('trn_type', sa.String(length=2), nullable=False),
    sa.Column('trn_timestamp', sa.DateTime(), nullable=False),
    sa.Column('trn_amount', sa.Integer(), nullable=False),
    sa.Column('trn_balance', sa.Integer(), nullable=True),
    sa.Column('trn_desc', sa.String(length=500), nullable=True),
    sa.Column('trn_by', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('trn_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('counselling_details',
    sa.Column('cnsl_id', sa.Integer(), nullable=False),
    sa.Column('cnsl_cnslr_id', sa.Integer(), nullable=True),
    sa.Column('cnsl_sur_id', sa.Integer(), nullable=False),
    sa.Column('cnsl_type', sa.Integer(), nullable=False),
    sa.Column('cnsl_time', sa.DateTime(), nullable=False),
    sa.Column('cnsl_date', sa.DateTime(), nullable=False),
    sa.Column('cnsl_about', sa.String(length=500), nullable=False),
    sa.Column('cnsl_review_cnslrr', sa.String(length=500), nullable=False),
    sa.Column('cnsl_review_cnslee', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['cnsl_sur_id'], ['survivor_details.sur_id'], ),
    sa.PrimaryKeyConstraint('cnsl_id')
    )
    op.create_table('doctor_details',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('doc_name', sa.String(length=120), nullable=False),
    sa.Column('doc_hosp_id', sa.Integer(), nullable=True),
    sa.Column('doc_experience', sa.Integer(), nullable=True),
    sa.Column('doc_city', sa.String(length=120), nullable=True),
    sa.Column('doc_phone', sa.Integer(), nullable=True),
    sa.Column('doc_cnsl_prvdr', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['doc_hosp_id'], ['hospital_details.hosp_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('stay_details',
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('stay_name', sa.String(length=120), nullable=False),
    sa.Column('stay_location', sa.String(length=500), nullable=False),
    sa.Column('stay_city', sa.String(length=100), nullable=False),
    sa.Column('stay_total_room_count', sa.Integer(), nullable=False),
    sa.Column('stay_avlbl_room_count', sa.Integer(), nullable=False),
    sa.Column('stay_bed_count', sa.Integer(), nullable=False),
    sa.Column('stay_cost_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stay_cost_id'], ['cost_details.cost_id'], ),
    sa.PrimaryKeyConstraint('stay_id')
    )
    op.create_table('booking_details',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_stay_id', sa.Integer(), nullable=True),
    sa.Column('book_day_count', sa.Integer(), nullable=False),
    sa.Column('book_start_date', sa.DateTime(), nullable=False),
    sa.Column('book_end_date', sa.DateTime(), nullable=False),
    sa.Column('book_total_cost', sa.Integer(), nullable=False),
    sa.Column('book_refund_cost', sa.Integer(), nullable=False),
    sa.Column('book_sur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_stay_id'], ['stay_details.stay_id'], ),
    sa.ForeignKeyConstraint(['book_sur_id'], ['survivor_details.sur_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('donation_details',
    sa.Column('don_id', sa.Integer(), nullable=False),
    sa.Column('don_amount', sa.Integer(), nullable=True),
    sa.Column('don_date', sa.DateTime(), nullable=False),
    sa.Column('don_by', sa.String(length=120), nullable=False),
    sa.Column('don_city', sa.Integer(), nullable=False),
    sa.Column('don_sur_id', sa.Integer(), nullable=True),
    sa.Column('don_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['don_doc_id'], ['doctor_details.doc_id'], ),
    sa.ForeignKeyConstraint(['don_sur_id'], ['survivor_details.sur_id'], ),
    sa.PrimaryKeyConstraint('don_id')
    )
    op.create_table('support_meeting_details',
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('meet_name', sa.String(length=120), nullable=True),
    sa.Column('meet_city', sa.Integer(), nullable=False),
    sa.Column('meet_address', sa.String(length=500), nullable=False),
    sa.Column('meet_start_date', sa.DateTime(), nullable=False),
    sa.Column('meet_end_date', sa.DateTime(), nullable=False),
    sa.Column('meet_cost_id', sa.Integer(), nullable=True),
    sa.Column('meet_start_time', sa.DateTime(), nullable=False),
    sa.Column('meet_end_time', sa.DateTime(), nullable=False),
    sa.Column('meet_food', sa.String(), nullable=False),
    sa.Column('meet_doc_id', sa.Integer(), nullable=False),
    sa.Column('meet_coord_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meet_coord_id'], ['member_details.mem_id'], ),
    sa.ForeignKeyConstraint(['meet_cost_id'], ['cost_details.cost_id'], ),
    sa.ForeignKeyConstraint(['meet_doc_id'], ['doctor_details.doc_id'], ),
    sa.PrimaryKeyConstraint('meet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_meeting_details')
    op.drop_table('donation_details')
    op.drop_table('booking_details')
    op.drop_table('stay_details')
    op.drop_table('doctor_details')
    op.drop_table('counselling_details')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('transaction_details')
    op.drop_table('survivor_details')
    op.drop_table('message_details')
    op.drop_table('member_details')
    op.drop_table('medicine_details')
    op.drop_table('hospital_details')
    op.drop_table('cost_details')
    op.drop_table('author_details')
    op.drop_table('articles_details')
    # ### end Alembic commands ###
