"""empty message

Revision ID: 7c7979833907
Revises: e7a968b06de4
Create Date: 2020-02-04 18:00:11.556864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7979833907'
down_revision = 'e7a968b06de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_class', sa.Column('board_det_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board_class', 'board_detail', ['board_det_id'], ['board_det_id'])
    op.add_column('board_class_subject', sa.Column('board_det_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board_class_subject', 'board_detail', ['board_det_id'], ['board_det_id'])
    op.add_column('book_details', sa.Column('board_det_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_details', 'board_detail', ['board_det_id'], ['board_det_id'])
    op.add_column('chapter_detail', sa.Column('board_det_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapter_detail', 'board_detail', ['board_det_id'], ['board_det_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter_detail', type_='foreignkey')
    op.drop_column('chapter_detail', 'board_det_id')
    op.drop_constraint(None, 'book_details', type_='foreignkey')
    op.drop_column('book_details', 'board_det_id')
    op.drop_constraint(None, 'board_class_subject', type_='foreignkey')
    op.drop_column('board_class_subject', 'board_det_id')
    op.drop_constraint(None, 'board_class', type_='foreignkey')
    op.drop_column('board_class', 'board_det_id')
    # ### end Alembic commands ###
