"""empty message

Revision ID: 7e4f448e2d6d
Revises: 571070a21a76
Create Date: 2019-06-11 16:50:23.834299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4f448e2d6d'
down_revision = '571070a21a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_section', sa.Column('classVal', sa.Integer(), nullable=True))
    op.add_column('class_section', sa.Column('section', sa.String(length=1), nullable=True))
    op.drop_constraint('class_section_class_id_fkey', 'class_section', type_='foreignkey')
    op.drop_constraint('class_section_section_id_fkey', 'class_section', type_='foreignkey')
    op.drop_column('class_section', 'class_id')
    op.drop_column('class_section', 'section_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_section', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('class_section', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('class_section_section_id_fkey', 'class_section', 'message_detail', ['section_id'], ['msg_id'])
    op.create_foreign_key('class_section_class_id_fkey', 'class_section', 'message_detail', ['class_id'], ['msg_id'])
    op.drop_column('class_section', 'section')
    op.drop_column('class_section', 'classVal')
    # ### end Alembic commands ###
