"""empty message

Revision ID: 7e786f8abf2c
Revises: 2d97973e436e
Create Date: 2020-06-04 17:51:25.910785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e786f8abf2c'
down_revision = '2d97973e436e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_detail', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'homework_detail', 'class_section', ['class_sec_id'], ['class_sec_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homework_detail', type_='foreignkey')
    op.drop_column('homework_detail', 'class_sec_id')
    # ### end Alembic commands ###
