"""empty message

Revision ID: 823f9d724e9a
Revises: c19d5c149b6f
Create Date: 2019-06-12 11:05:57.072880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823f9d724e9a'
down_revision = 'c19d5c149b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance', 'class_section', ['class_sec_id'], ['class_sec_id'])
    op.add_column('financial_details', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'financial_details', 'class_section', ['class_sec_id'], ['class_sec_id'])
    op.add_column('response_capture', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'response_capture', 'class_section', ['class_sec_id'], ['class_sec_id'])
    op.add_column('result_upload', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'result_upload', 'class_section', ['class_sec_id'], ['class_sec_id'])
    op.add_column('school_fee_mgt', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'school_fee_mgt', 'class_section', ['class_sec_id'], ['class_sec_id'])
    op.add_column('student_profile', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_profile', 'class_section', ['class_sec_id'], ['class_sec_id'])
    op.add_column('teacher_profile', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher_profile', 'class_section', ['class_sec_id'], ['class_sec_id'])
    op.add_column('topic_tracker', sa.Column('class_sec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic_tracker', 'class_section', ['class_sec_id'], ['class_sec_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_tracker', type_='foreignkey')
    op.drop_column('topic_tracker', 'class_sec_id')
    op.drop_constraint(None, 'teacher_profile', type_='foreignkey')
    op.drop_column('teacher_profile', 'class_sec_id')
    op.drop_constraint(None, 'student_profile', type_='foreignkey')
    op.drop_column('student_profile', 'class_sec_id')
    op.drop_constraint(None, 'school_fee_mgt', type_='foreignkey')
    op.drop_column('school_fee_mgt', 'class_sec_id')
    op.drop_constraint(None, 'result_upload', type_='foreignkey')
    op.drop_column('result_upload', 'class_sec_id')
    op.drop_constraint(None, 'response_capture', type_='foreignkey')
    op.drop_column('response_capture', 'class_sec_id')
    op.drop_constraint(None, 'financial_details', type_='foreignkey')
    op.drop_column('financial_details', 'class_sec_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'class_sec_id')
    # ### end Alembic commands ###
