"""empty message

Revision ID: 8372fb7195bb
Revises: 
Create Date: 2020-06-07 04:40:23.399851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8372fb7195bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_class',
    sa.Column('live_class_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=30), nullable=False),
    sa.Column('end_time', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=100), nullable=True),
    sa.Column('conf_link', sa.String(length=200), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], ),
    sa.PrimaryKeyConstraint('live_class_id')
    )
    op.alter_column('board_class_subject_books', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('board_class_subject_books', 'class_val',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('board_class_subject_books', 'is_archived',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('board_class_subject_books', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('homework_detail', sa.Column('attachment', sa.String(length=200), nullable=True))
    op.add_column('homework_questions', sa.Column('ref_type', sa.Integer(), nullable=True))
    op.add_column('homework_questions', sa.Column('ref_url', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'homework_questions', 'message_detail', ['ref_type'], ['msg_id'])
    op.add_column('module_access', sa.Column('is_archived', sa.String(length=1), nullable=False))
    op.add_column('module_access', sa.Column('module_name', sa.String(length=50), nullable=True))
    op.add_column('module_detail', sa.Column('is_archived', sa.String(length=1), nullable=False))
    op.add_column('module_detail', sa.Column('module_type', sa.Integer(), nullable=True))
    op.add_column('module_detail', sa.Column('module_url', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'module_detail', 'message_detail', ['module_type'], ['msg_id'])
    op.drop_column('module_detail', 'page_link')
    op.add_column('student_homework_response', sa.Column('teacher_remark', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_homework_response', 'teacher_remark')
    op.add_column('module_detail', sa.Column('page_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'module_detail', type_='foreignkey')
    op.drop_column('module_detail', 'module_url')
    op.drop_column('module_detail', 'module_type')
    op.drop_column('module_detail', 'is_archived')
    op.drop_column('module_access', 'module_name')
    op.drop_column('module_access', 'is_archived')
    op.drop_constraint(None, 'homework_questions', type_='foreignkey')
    op.drop_column('homework_questions', 'ref_url')
    op.drop_column('homework_questions', 'ref_type')
    op.drop_column('homework_detail', 'attachment')
    op.alter_column('board_class_subject_books', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('board_class_subject_books', 'is_archived',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('board_class_subject_books', 'class_val',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('board_class_subject_books', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('live_class')
    # ### end Alembic commands ###
