"""empty message

Revision ID: 84396b2a292a
Revises: 7e4f448e2d6d
Create Date: 2019-06-11 17:06:15.840984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84396b2a292a'
down_revision = '7e4f448e2d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_section', sa.Column('class_val', sa.Integer(), nullable=True))
    op.drop_column('class_section', 'classVal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_section', sa.Column('classVal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('class_section', 'class_val')
    # ### end Alembic commands ###
