"""empty message

Revision ID: 846789698289
Revises: b2957b499e06
Create Date: 2020-04-14 13:24:16.403024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846789698289'
down_revision = 'b2957b499e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_class_subject_books',
    sa.Column('bcsb_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_val', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('is_archieve', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book_details.book_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('bcsb_id')
    )
    op.add_column('board_class_subject', sa.Column('is_archived', sa.String(length=1), nullable=True))
    op.add_column('board_class_subject', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board_class_subject', 'school_profile', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_class_subject', type_='foreignkey')
    op.drop_column('board_class_subject', 'school_id')
    op.drop_column('board_class_subject', 'is_archived')
    op.drop_table('board_class_subject_books')
    # ### end Alembic commands ###
