"""empty message

Revision ID: 86eb054b2d34
Revises: aaf0a3601fbd
Create Date: 2019-06-28 18:56:41.709478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86eb054b2d34'
down_revision = 'aaf0a3601fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('response_capture_response_option_fkey', 'response_capture', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('response_capture_response_option_fkey', 'response_capture', 'question_options', ['response_option'], ['option_id'])
    # ### end Alembic commands ###
