"""empty message

Revision ID: 87b0239ffb16
Revises: 
Create Date: 2020-08-27 15:48:02.086908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b0239ffb16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_topics', 'video_class_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_topics', sa.Column('video_class_url', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
