"""empty message

Revision ID: 88cdacd07950
Revises: 33a7e1157999
Create Date: 2019-06-27 12:32:11.440597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cdacd07950'
down_revision = '33a7e1157999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('student_first_name', sa.String(length=50), nullable=True))
    op.add_column('student_profile', sa.Column('student_full_name', sa.String(length=200), nullable=True))
    op.add_column('student_profile', sa.Column('student_last_name', sa.String(length=50), nullable=True))
    op.drop_column('student_profile', 'student_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('student_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('student_profile', 'student_last_name')
    op.drop_column('student_profile', 'student_full_name')
    op.drop_column('student_profile', 'student_first_name')
    # ### end Alembic commands ###
