"""empty message

Revision ID: 8bd47b541678
Revises: bc05ce051205
Create Date: 2019-06-11 17:31:48.401331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd47b541678'
down_revision = 'bc05ce051205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slide_tracker_topic_id_fkey', 'slide_tracker', type_='foreignkey')
    op.create_foreign_key(None, 'slide_tracker', 'topic_detail', ['topic_id'], ['topic_id'])
    op.drop_constraint('topic_tracker_topic_id_fkey', 'topic_tracker', type_='foreignkey')
    op.create_foreign_key(None, 'topic_tracker', 'topic_detail', ['topic_id'], ['topic_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_tracker', type_='foreignkey')
    op.create_foreign_key('topic_tracker_topic_id_fkey', 'topic_tracker', 'message_detail', ['topic_id'], ['msg_id'])
    op.drop_constraint(None, 'slide_tracker', type_='foreignkey')
    op.create_foreign_key('slide_tracker_topic_id_fkey', 'slide_tracker', 'message_detail', ['topic_id'], ['msg_id'])
    # ### end Alembic commands ###
