"""empty message

Revision ID: 8eceacd661c7
Revises: e1f6cac643af
Create Date: 2019-06-16 15:07:08.401823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eceacd661c7'
down_revision = 'e1f6cac643af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_avatar')
    # ### end Alembic commands ###
