"""empty message

Revision ID: 91e378a771d8
Revises: f28561bcba24
Create Date: 2019-06-29 14:31:17.667812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e378a771d8'
down_revision = 'f28561bcba24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('resp_session_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_capture', 'resp_session_id')
    # ### end Alembic commands ###
