"""empty message

Revision ID: 91f83f684510
Revises: d7506849832e
Create Date: 2019-10-22 19:08:58.972507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f83f684510'
down_revision = 'd7506849832e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_detail', sa.Column('student_limit', sa.Integer(), nullable=True))
    op.add_column('subscription_detail', sa.Column('sub_desc', sa.String(length=500), nullable=True))
    op.add_column('subscription_detail', sa.Column('teacher_limit', sa.Integer(), nullable=True))
    op.add_column('subscription_detail', sa.Column('test_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_detail', 'test_limit')
    op.drop_column('subscription_detail', 'teacher_limit')
    op.drop_column('subscription_detail', 'sub_desc')
    op.drop_column('subscription_detail', 'student_limit')
    # ### end Alembic commands ###
