"""empty message

Revision ID: 92368cbd73fc
Revises: 0ce1237d81a6
Create Date: 2019-06-27 17:41:18.513855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92368cbd73fc'
down_revision = '0ce1237d81a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_qr_options',
    sa.Column('student_qr_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(length=1), nullable=True),
    sa.Column('qr_link', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('student_qr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_qr_options')
    # ### end Alembic commands ###
