"""empty message

Revision ID: 9377eacb2560
Revises: 4863aa216651
Create Date: 2019-09-15 15:36:08.637660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9377eacb2560'
down_revision = '4863aa216651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_detail', sa.Column('load_new_question', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_detail', 'load_new_question')
    # ### end Alembic commands ###
