"""empty message

Revision ID: 97ea0741acc1
Revises: d1647e936e9e
Create Date: 2019-06-20 13:53:20.842990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ea0741acc1'
down_revision = 'd1647e936e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_details', sa.Column('class_val', sa.Integer(), nullable=True))
    op.drop_constraint('question_details_class_id_fkey', 'question_details', type_='foreignkey')
    op.drop_column('question_details', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_details', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('question_details_class_id_fkey', 'question_details', 'message_detail', ['class_id'], ['msg_id'])
    op.drop_column('question_details', 'class_val')
    # ### end Alembic commands ###
