"""empty message

Revision ID: 99dcf9f30aa1
Revises: e46a85870570
Create Date: 2019-09-26 13:45:12.859788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dcf9f30aa1'
down_revision = 'e46a85870570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_detail', sa.Column('class_val', sa.Integer(), nullable=True))
    op.add_column('content_detail', sa.Column('is_private', sa.String(length=1), nullable=True))
    op.add_column('content_detail', sa.Column('last_modified_date', sa.DateTime(), nullable=True))
    op.add_column('content_detail', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('content_detail', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'content_detail', 'message_detail', ['subject_id'], ['msg_id'])
    op.create_foreign_key(None, 'content_detail', 'teacher_profile', ['uploaded_by'], ['teacher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_detail', type_='foreignkey')
    op.drop_constraint(None, 'content_detail', type_='foreignkey')
    op.drop_column('content_detail', 'uploaded_by')
    op.drop_column('content_detail', 'subject_id')
    op.drop_column('content_detail', 'last_modified_date')
    op.drop_column('content_detail', 'is_private')
    op.drop_column('content_detail', 'class_val')
    # ### end Alembic commands ###
