"""empty message

Revision ID: 9a117e4d859c
Revises: 47e2788eb31e
Create Date: 2019-07-15 12:41:35.707040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a117e4d859c'
down_revision = '47e2788eb31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_details', sa.Column('suggested_weightage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_details', 'suggested_weightage')
    # ### end Alembic commands ###
