"""empty message

Revision ID: 9aae9a9d4d1c
Revises: 
Create Date: 2020-06-08 17:07:15.138756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9aae9a9d4d1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_class')
    op.add_column('board_class_subject', sa.Column('board_det_id', sa.Integer(), nullable=True))
    op.alter_column('board_class_subject', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'board_class_subject', 'board_detail', ['board_det_id'], ['board_det_id'])
    op.drop_column('homework_detail', 'attachment')
    op.add_column('homework_questions', sa.Column('hq_id', sa.Integer(), nullable=False))
    op.drop_constraint('homework_questions_ref_type_fkey', 'homework_questions', type_='foreignkey')
    op.drop_column('homework_questions', 'ref_type')
    op.drop_column('homework_questions', 'sq_id')
    op.drop_column('homework_questions', 'ref_url')
    op.drop_column('module_access', 'is_archived')
    op.drop_column('module_access', 'module_name')
    op.add_column('module_detail', sa.Column('page_link', sa.String(length=200), nullable=True))
    op.drop_constraint('module_detail_module_type_fkey', 'module_detail', type_='foreignkey')
    op.drop_column('module_detail', 'module_type')
    op.drop_column('module_detail', 'is_archived')
    op.drop_column('module_detail', 'module_url')
    op.add_column('student_homework_response', sa.Column('hq_id', sa.Integer(), nullable=False))
    op.drop_constraint('student_homework_response_sq_id_fkey', 'student_homework_response', type_='foreignkey')
    op.create_foreign_key(None, 'student_homework_response', 'homework_questions', ['hq_id'], ['hq_id'])
    op.drop_column('student_homework_response', 'teacher_remark')
    op.drop_column('student_homework_response', 'sq_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_homework_response', sa.Column('sq_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('student_homework_response', sa.Column('teacher_remark', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_homework_response', type_='foreignkey')
    op.create_foreign_key('student_homework_response_sq_id_fkey', 'student_homework_response', 'homework_questions', ['sq_id'], ['sq_id'])
    op.drop_column('student_homework_response', 'hq_id')
    op.add_column('module_detail', sa.Column('module_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('module_detail', sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('module_detail', sa.Column('module_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('module_detail_module_type_fkey', 'module_detail', 'message_detail', ['module_type'], ['msg_id'])
    op.drop_column('module_detail', 'page_link')
    op.add_column('module_access', sa.Column('module_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('module_access', sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('homework_questions', sa.Column('ref_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('homework_questions', sa.Column('sq_id', sa.INTEGER(), server_default=sa.text("nextval('homework_questions_sq_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('homework_questions', sa.Column('ref_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('homework_questions_ref_type_fkey', 'homework_questions', 'message_detail', ['ref_type'], ['msg_id'])
    op.drop_column('homework_questions', 'hq_id')
    op.add_column('homework_detail', sa.Column('attachment', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'board_class_subject', type_='foreignkey')
    op.alter_column('board_class_subject', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('board_class_subject', 'board_det_id')
    op.create_table('live_class',
    sa.Column('live_class_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_sec_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('conf_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], name='live_class_class_sec_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='live_class_school_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], name='live_class_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], name='live_class_teacher_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], name='live_class_topic_id_fkey'),
    sa.PrimaryKeyConstraint('live_class_id', name='live_class_pkey')
    )
    # ### end Alembic commands ###
