"""empty message

Revision ID: 9d5fc8ed7c3a
Revises: caa2573131be
Create Date: 2019-11-06 14:45:03.849305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5fc8ed7c3a'
down_revision = 'caa2573131be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('intro_link', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'intro_link')
    # ### end Alembic commands ###
