"""empty message

Revision ID: 9d89b8c8bbf2
Revises: 493e4bb32500
Create Date: 2020-08-23 15:43:06.499040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d89b8c8bbf2'
down_revision = '493e4bb32500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'topic_detail', ['topic_id'], ['topic_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'topic_id')
    # ### end Alembic commands ###
