"""empty message

Revision ID: 9ee0732709fc
Revises: b50ac04d2102
Create Date: 2019-06-17 22:47:25.427441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee0732709fc'
down_revision = 'b50ac04d2102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_details', sa.Column('class_val', sa.Integer(), nullable=True))
    op.drop_constraint('book_details_class_id_fkey', 'book_details', type_='foreignkey')
    op.drop_column('book_details', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_details', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_details_class_id_fkey', 'book_details', 'message_detail', ['class_id'], ['msg_id'])
    op.drop_column('book_details', 'class_val')
    # ### end Alembic commands ###
