"""empty message

Revision ID: a8fd4d6d9371
Revises: d21d72d54a5f
Create Date: 2020-04-16 21:36:45.882003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8fd4d6d9371'
down_revision = 'd21d72d54a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_survey_response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_survey_response',
    sa.Column('survey_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sq_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('survey_response_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sq_id'], ['survey_questions.sq_id'], name='student_survey_response_sq_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name='student_survey_response_student_id_fkey'),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_detail.survey_id'], name='student_survey_response_survey_id_fkey')
    )
    # ### end Alembic commands ###
