"""empty message

Revision ID: aa9f1c115357
Revises: 961cdd281874
Create Date: 2020-06-07 04:08:09.976614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa9f1c115357'
down_revision = '961cdd281874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_module_mapping')
    op.drop_table('module_mapping')
    op.add_column('module_access', sa.Column('is_archived', sa.String(length=1), nullable=False))
    op.add_column('module_access', sa.Column('module_name', sa.String(length=50), nullable=True))
    op.add_column('module_detail', sa.Column('is_archived', sa.String(length=1), nullable=False))
    op.add_column('module_detail', sa.Column('module_type', sa.Integer(), nullable=True))
    op.add_column('module_detail', sa.Column('module_url', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'module_detail', 'message_detail', ['module_type'], ['msg_id'])
    op.drop_column('module_detail', 'page_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_detail', sa.Column('page_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'module_detail', type_='foreignkey')
    op.drop_column('module_detail', 'module_url')
    op.drop_column('module_detail', 'module_type')
    op.drop_column('module_detail', 'is_archived')
    op.drop_column('module_access', 'module_name')
    op.drop_column('module_access', 'is_archived')
    op.create_table('module_mapping',
    sa.Column('module_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('module_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_type'], ['message_detail.msg_id'], name='module_mapping_module_type_fkey'),
    sa.PrimaryKeyConstraint('module_id', name='module_mapping_pkey')
    )
    op.create_table('user_module_mapping',
    sa.Column('umm_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module_detail.module_id'], name='user_module_mapping_module_id_fkey'),
    sa.ForeignKeyConstraint(['user_type'], ['message_detail.msg_id'], name='user_module_mapping_user_type_fkey'),
    sa.PrimaryKeyConstraint('umm_id', name='user_module_mapping_pkey')
    )
    # ### end Alembic commands ###
