"""empty message

Revision ID: aae86f6dfc0c
Revises: 
Create Date: 2021-01-12 20:19:31.231680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae86f6dfc0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_detail', sa.Column('instructions', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_detail', 'instructions')
    # ### end Alembic commands ###
