"""empty message

Revision ID: aaf0a3601fbd
Revises: 92368cbd73fc
Create Date: 2019-06-27 17:48:56.007677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf0a3601fbd'
down_revision = '92368cbd73fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_options', sa.Column('option', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_options', 'option')
    # ### end Alembic commands ###
