"""empty message

Revision ID: aec3076b3b76
Revises: 057582631fa1
Create Date: 2020-04-16 17:00:20.670187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec3076b3b76'
down_revision = '057582631fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_detail', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'survey_detail', 'school_profile', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_detail', type_='foreignkey')
    op.drop_column('survey_detail', 'school_id')
    # ### end Alembic commands ###
