"""empty message

Revision ID: af6a33ec0f4d
Revises: 
Create Date: 2021-01-12 20:03:11.396698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6a33ec0f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_detail', sa.Column('instructions', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_detail', 'instructions')
    # ### end Alembic commands ###
