"""empty message

Revision ID: afa7cb274c6b
Revises: 58898dbfe819
Create Date: 2020-08-22 11:52:57.852535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa7cb274c6b'
down_revision = '58898dbfe819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_batch', sa.Column('fee_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_batch', 'message_detail', ['fee_type'], ['msg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_batch', type_='foreignkey')
    op.drop_column('course_batch', 'fee_type')
    # ### end Alembic commands ###
