"""empty message

Revision ID: b089e371ff54
Revises: f859135f02d4
Create Date: 2020-08-19 15:43:02.166200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b089e371ff54'
down_revision = 'f859135f02d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_batch', sa.Column('students_enrolled', sa.Integer(), nullable=True))
    op.add_column('course_batch', sa.Column('total_fee_received', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_batch', 'total_fee_received')
    op.drop_column('course_batch', 'students_enrolled')
    # ### end Alembic commands ###
