"""empty message

Revision ID: b167fdbd6b1e
Revises: 
Create Date: 2019-05-27 22:15:21.128483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b167fdbd6b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alllearn_school_perf',
    sa.Column('all_perf_id', sa.Integer(), nullable=False),
    sa.Column('avg_perf_alllearn', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('all_perf_id')
    )
    op.create_table('class_section',
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=1), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('class_teacher', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('class_sec_id')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.DateTime(), nullable=True),
    sa.Column('is_present', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_table('book_details',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=True),
    sa.Column('book_name', sa.String(length=120), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('calendar',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('date_aging', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('week_aging', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.Integer(), nullable=False),
    sa.Column('month_aging', sa.Integer(), nullable=False),
    sa.Column('semi_annual', sa.Integer(), nullable=False),
    sa.Column('semi_annual_aging', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('year_aging', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_table('content',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.String(length=120), nullable=False),
    sa.Column('chapter_name', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.String(length=120), nullable=False),
    sa.Column('board_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('content_tracker',
    sa.Column('cont_track_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=True),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.Column('last_modified_Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cont_track_id')
    )
    op.create_table('event_detail',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('event_duration_hours', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('event_color', sa.DateTime(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('financial_details',
    sa.Column('fin_det_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('subscription_amt', sa.Integer(), nullable=False),
    sa.Column('maint_cost', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fin_det_id')
    )
    op.create_table('message_detail',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('performance_detail',
    sa.Column('perf_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=1), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semi_annual', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('school_avg_score', sa.Integer(), nullable=False),
    sa.Column('class_avg_score', sa.Integer(), nullable=False),
    sa.Column('section_avg_score', sa.Integer(), nullable=False),
    sa.Column('student_score', sa.Integer(), nullable=False),
    sa.Column('school_year_rank', sa.Integer(), nullable=False),
    sa.Column('school_semi_annual_rank', sa.Integer(), nullable=False),
    sa.Column('school_month_rank', sa.Integer(), nullable=False),
    sa.Column('class_year_rank', sa.Integer(), nullable=False),
    sa.Column('section_year_rank', sa.Integer(), nullable=False),
    sa.Column('section_semi_annual_rank', sa.Integer(), nullable=False),
    sa.Column('student_year_rank', sa.Integer(), nullable=False),
    sa.Column('student_semi_annual_rank', sa.Integer(), nullable=False),
    sa.Column('student_month_rank', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('perf_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('question_details',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=False),
    sa.Column('board_name', sa.String(length=120), nullable=False),
    sa.Column('question_description', sa.String(length=500), nullable=False),
    sa.Column('slideshow_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=120), nullable=False),
    sa.Column('references', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('question_options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('option_desc', sa.String(length=500), nullable=False),
    sa.Column('option_type', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=False),
    sa.Column('weightage', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_table('recomm_detail',
    sa.Column('recomm_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Integer(), nullable=False),
    sa.Column('if_this', sa.String(length=500), nullable=False),
    sa.Column('then_this', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('recomm_id')
    )
    op.create_table('response_capture',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('slideshow_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_option', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('result_upload',
    sa.Column('res_upload_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=True),
    sa.Column('is_present', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('test_type', sa.Integer(), nullable=False),
    sa.Column('marks_scored', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('res_upload_id')
    )
    op.create_table('school_fee_mgt',
    sa.Column('fee_trans_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('fee_amount', sa.Integer(), nullable=False),
    sa.Column('fee_paid_amount', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Integer(), nullable=False),
    sa.Column('delay_reason', sa.Integer(), nullable=False),
    sa.Column('outstanding_amount', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('fee_trans_id')
    )
    op.create_table('school_profile',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=500), nullable=False),
    sa.Column('registered_date', sa.DateTime(), nullable=False),
    sa.Column('org_leaving_Date', sa.DateTime(), nullable=True),
    sa.Column('org_leaving_reason', sa.String(length=500), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['state'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('search',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('search_keywords', sa.String(length=100), nullable=False),
    sa.Column('search_date', sa.DateTime(), nullable=False),
    sa.Column('is_error_page', sa.Integer(), nullable=False),
    sa.Column('redirect_url', sa.String(length=500), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('search_id')
    )
    op.create_table('slide_tracker',
    sa.Column('slideshow_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=False),
    sa.Column('chapter_id', sa.String(length=120), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('slideshow_id')
    )
    op.create_table('student_profile',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('leaving_date', sa.DateTime(), nullable=True),
    sa.Column('leaving_reason', sa.String(length=500), nullable=True),
    sa.Column('roll_number', sa.Integer(), nullable=True),
    sa.Column('school_adm_number', sa.String(length=120), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('survivor_details',
    sa.Column('sur_id', sa.Integer(), nullable=False),
    sa.Column('sur_name', sa.String(length=120), nullable=False),
    sa.Column('sur_email', sa.String(length=120), nullable=False),
    sa.Column('sur_treatment_status', sa.String(length=120), nullable=True),
    sa.Column('sur_address', sa.String(length=500), nullable=True),
    sa.Column('sur_city', sa.Integer(), nullable=True),
    sa.Column('sur_cnsl_prvdr', sa.String(length=2), nullable=True),
    sa.Column('sur_cnsl_require', sa.String(length=2), nullable=True),
    sa.Column('sur_phone', sa.Integer(), nullable=True),
    sa.Column('sur_gender', sa.String(length=2), nullable=True),
    sa.Column('sur_age', sa.Integer(), nullable=True),
    sa.Column('sur_newsletter', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('sur_id')
    )
    op.create_table('teacher_profile',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=500), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('school_leaving_date', sa.DateTime(), nullable=True),
    sa.Column('school_leaving_reason', sa.String(length=500), nullable=False),
    sa.Column('profile_picture', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('test_details',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=120), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=120), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=3), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('test_questions',
    sa.Column('tq_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tq_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('test_questions')
    op.drop_table('test_details')
    op.drop_table('teacher_profile')
    op.drop_table('survivor_details')
    op.drop_table('student_profile')
    op.drop_table('slide_tracker')
    op.drop_table('search')
    op.drop_table('school_profile')
    op.drop_table('school_fee_mgt')
    op.drop_table('result_upload')
    op.drop_table('response_capture')
    op.drop_table('recomm_detail')
    op.drop_table('question_options')
    op.drop_table('question_details')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('performance_detail')
    op.drop_table('message_detail')
    op.drop_table('financial_details')
    op.drop_table('event_detail')
    op.drop_table('content_tracker')
    op.drop_table('content')
    op.drop_table('class_section')
    op.drop_table('calendar')
    op.drop_table('book_details')
    op.drop_table('attendance')
    op.drop_table('alllearn_school_perf')
    # ### end Alembic commands ###
