"""empty message

Revision ID: b23b4ab0f114
Revises: e2cab87dbcbc
Create Date: 2019-10-22 22:25:37.643511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23b4ab0f114'
down_revision = 'e2cab87dbcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_detail', sa.Column('group_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_detail', 'group_name')
    # ### end Alembic commands ###
