"""empty message

Revision ID: b2957b499e06
Revises: b1053a36d513
Create Date: 2020-04-14 06:28:04.514926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2957b499e06'
down_revision = 'b1053a36d513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_payroll_detail', 'teacher_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_payroll_detail', sa.Column('teacher_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
