"""empty message

Revision ID: b32ff402275d
Revises: deda469544ac
Create Date: 2019-06-18 16:06:33.232216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32ff402275d'
down_revision = 'deda469544ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('cover_Date', sa.DateTime(), nullable=True))
    op.add_column('topic_tracker', sa.Column('is_covered', sa.String(length=1), nullable=True))
    op.add_column('topic_tracker', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.drop_constraint('topic_tracker_last_topic_fkey', 'topic_tracker', type_='foreignkey')
    op.create_foreign_key(None, 'topic_tracker', 'topic_detail', ['topic_id'], ['topic_id'])
    op.drop_column('topic_tracker', 'last_topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_tracker', sa.Column('last_topic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topic_tracker', type_='foreignkey')
    op.create_foreign_key('topic_tracker_last_topic_fkey', 'topic_tracker', 'topic_detail', ['last_topic'], ['topic_id'])
    op.drop_column('topic_tracker', 'topic_id')
    op.drop_column('topic_tracker', 'is_covered')
    op.drop_column('topic_tracker', 'cover_Date')
    # ### end Alembic commands ###
