"""empty message

Revision ID: b34f95795c8d
Revises: bd079684cf12
Create Date: 2019-10-10 16:03:42.282012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34f95795c8d'
down_revision = 'bd079684cf12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_profile', sa.Column('school_admin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'school_profile', 'teacher_profile', ['school_admin'], ['teacher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_profile', type_='foreignkey')
    op.drop_column('school_profile', 'school_admin')
    # ### end Alembic commands ###
