"""empty message

Revision ID: b362a53980a7
Revises: 9aa1320bc988
Create Date: 2019-06-11 20:02:58.653337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b362a53980a7'
down_revision = '9aa1320bc988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('class_section')
    
# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_section',
    sa.Column('class_sec_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_teacher', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('class_val', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_teacher'], ['teacher_profile.teacher_id'], name='class_section_class_teacher_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='class_section_school_id_fkey'),
    sa.PrimaryKeyConstraint('class_sec_id', name='class_section_pkey')
    )
    # ### end Alembic commands ###
