"""empty message

Revision ID: b50ac04d2102
Revises: 18bfe399e3a8
Create Date: 2019-06-17 22:29:41.935771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50ac04d2102'
down_revision = '18bfe399e3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_details', sa.Column('book_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_details', 'book_link')
    # ### end Alembic commands ###
