"""empty message

Revision ID: b888e9c61376
Revises: 50e334a2955f
Create Date: 2019-06-29 13:49:09.340449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b888e9c61376'
down_revision = '50e334a2955f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('resp_session_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_capture', 'resp_session_id')
    # ### end Alembic commands ###
