"""empty message

Revision ID: bbd6a7ee8e52
Revises: 9ee0732709fc
Create Date: 2019-06-17 22:54:39.719825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd6a7ee8e52'
down_revision = '9ee0732709fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_detail', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic_detail', 'book_details', ['book_id'], ['book_id'])
    op.drop_column('topic_detail', 'book_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_detail', sa.Column('book_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topic_detail', type_='foreignkey')
    op.drop_column('topic_detail', 'book_id')
    # ### end Alembic commands ###
