"""empty message

Revision ID: bc05ce051205
Revises: 84396b2a292a
Create Date: 2019-06-11 17:26:30.394892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc05ce051205'
down_revision = '84396b2a292a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_detail',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('topic_tracker',
    sa.Column('topic_track_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Integer(), nullable=True),
    sa.Column('last_modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('topic_track_id')
    )
    op.drop_table('content_tracker')
    op.drop_table('content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('content_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['message_detail.msg_id'], name='content_board_id_fkey'),
    sa.ForeignKeyConstraint(['chapter_id'], ['message_detail.msg_id'], name='content_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['class_id'], ['message_detail.msg_id'], name='content_class_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], name='content_subject_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['message_detail.msg_id'], name='content_topic_id_fkey'),
    sa.PrimaryKeyConstraint('content_id', name='content_pkey')
    )
    op.create_table('content_tracker',
    sa.Column('cont_track_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_sec_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], name='content_tracker_class_sec_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='content_tracker_school_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], name='content_tracker_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], name='content_tracker_teacher_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['message_detail.msg_id'], name='content_tracker_topic_id_fkey'),
    sa.PrimaryKeyConstraint('cont_track_id', name='content_tracker_pkey')
    )
    op.drop_table('topic_tracker')
    op.drop_table('topic_detail')
    # ### end Alembic commands ###
