"""empty message

Revision ID: bd079684cf12
Revises: 681dcadaf46e
Create Date: 2019-10-10 15:39:54.802979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd079684cf12'
down_revision = '681dcadaf46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_access',
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module_detail.module_id'], ),
    sa.ForeignKeyConstraint(['user_type'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('access_id')
    )
    op.create_table('student_tag',
    sa.Column('stud_tag_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('archive_status', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_detail.tag_id'], ),
    sa.PrimaryKeyConstraint('stud_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_tag')
    op.drop_table('module_access')
    # ### end Alembic commands ###
