"""empty message

Revision ID: bddc01733cef
Revises: 07aab7a9d5d1
Create Date: 2020-08-13 14:48:01.758007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddc01733cef'
down_revision = '07aab7a9d5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_enrollment',
    sa.Column('ce_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['course_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course_detail.course_id'], ),
    sa.ForeignKeyConstraint(['student_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('ce_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_enrollment')
    # ### end Alembic commands ###
