"""empty message

Revision ID: be8837e7b86a
Revises: a9723c594c45
Create Date: 2019-05-27 23:42:43.347475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8837e7b86a'
down_revision = 'a9723c594c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attendance', 'message_detail', ['subject_id'], ['msg_id'])
    op.add_column('book_details', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book_details', 'message_detail', ['subject_id'], ['msg_id'])
    op.add_column('class_section', sa.Column('section_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'class_section', 'message_detail', ['section_id'], ['msg_id'])
    op.add_column('content', sa.Column('chapter_id', sa.Integer(), nullable=False))
    op.add_column('content', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('content', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'content', 'message_detail', ['topic_id'], ['msg_id'])
    op.create_foreign_key(None, 'content', 'message_detail', ['subject_id'], ['msg_id'])
    op.create_foreign_key(None, 'content', 'message_detail', ['chapter_id'], ['msg_id'])
    op.add_column('content_tracker', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('content_tracker', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'content_tracker', 'message_detail', ['subject_id'], ['msg_id'])
    op.create_foreign_key(None, 'content_tracker', 'message_detail', ['topic_id'], ['msg_id'])
    op.add_column('performance_detail', sa.Column('section_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'performance_detail', 'message_detail', ['section_id'], ['msg_id'])
    op.add_column('question_details', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'question_details', 'message_detail', ['subject_id'], ['msg_id'])
    op.add_column('response_capture', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'response_capture', 'message_detail', ['subject_id'], ['msg_id'])
    op.add_column('result_upload', sa.Column('class_sec_id', sa.Integer(), nullable=False))
    op.add_column('result_upload', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'result_upload', 'message_detail', ['subject_id'], ['msg_id'])
    op.create_foreign_key(None, 'result_upload', 'class_section', ['class_sec_id'], ['class_sec_id'])
    op.add_column('slide_tracker', sa.Column('chapter_id', sa.Integer(), nullable=False))
    op.add_column('slide_tracker', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('slide_tracker', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'slide_tracker', 'message_detail', ['subject_id'], ['msg_id'])
    op.create_foreign_key(None, 'slide_tracker', 'message_detail', ['chapter_id'], ['msg_id'])
    op.create_foreign_key(None, 'slide_tracker', 'message_detail', ['topic_id'], ['msg_id'])
    op.add_column('teacher_profile', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher_profile', 'message_detail', ['subject_id'], ['msg_id'])
    op.add_column('test_details', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_details', 'message_detail', ['subject_id'], ['msg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_details', type_='foreignkey')
    op.drop_column('test_details', 'subject_id')
    op.drop_constraint(None, 'teacher_profile', type_='foreignkey')
    op.drop_column('teacher_profile', 'subject_id')
    op.drop_constraint(None, 'slide_tracker', type_='foreignkey')
    op.drop_constraint(None, 'slide_tracker', type_='foreignkey')
    op.drop_constraint(None, 'slide_tracker', type_='foreignkey')
    op.drop_column('slide_tracker', 'topic_id')
    op.drop_column('slide_tracker', 'subject_id')
    op.drop_column('slide_tracker', 'chapter_id')
    op.drop_constraint(None, 'result_upload', type_='foreignkey')
    op.drop_constraint(None, 'result_upload', type_='foreignkey')
    op.drop_column('result_upload', 'subject_id')
    op.drop_column('result_upload', 'class_sec_id')
    op.drop_constraint(None, 'response_capture', type_='foreignkey')
    op.drop_column('response_capture', 'subject_id')
    op.drop_constraint(None, 'question_details', type_='foreignkey')
    op.drop_column('question_details', 'subject_id')
    op.drop_constraint(None, 'performance_detail', type_='foreignkey')
    op.drop_column('performance_detail', 'section_id')
    op.drop_constraint(None, 'content_tracker', type_='foreignkey')
    op.drop_constraint(None, 'content_tracker', type_='foreignkey')
    op.drop_column('content_tracker', 'topic_id')
    op.drop_column('content_tracker', 'subject_id')
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'topic_id')
    op.drop_column('content', 'subject_id')
    op.drop_column('content', 'chapter_id')
    op.drop_constraint(None, 'class_section', type_='foreignkey')
    op.drop_column('class_section', 'section_id')
    op.drop_constraint(None, 'book_details', type_='foreignkey')
    op.drop_column('book_details', 'subject_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'subject_id')
    # ### end Alembic commands ###
