"""empty message

Revision ID: beb5a5eb4501
Revises: 86eb054b2d34
Create Date: 2019-06-28 19:11:43.725277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb5a5eb4501'
down_revision = '86eb054b2d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_capture', 'response_option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('response_option', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
