"""empty message

Revision ID: bfd4e313f599
Revises: ce7f5306888f
Create Date: 2019-12-28 19:03:58.893647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd4e313f599'
down_revision = 'ce7f5306888f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_class',
    sa.Column('board_class_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('class_val', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('board_class_id')
    )
    op.create_table('board_class_subject',
    sa.Column('bcs_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('class_val', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('bcs_id')
    )
    op.create_table('board_detail',
    sa.Column('board_det_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('board_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('board_type', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['board_type'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('board_det_id')
    )
    op.create_table('chapter_detail',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_num', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=120), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('bcs_id', sa.Integer(), nullable=True),
    sa.Column('book_name', sa.String(length=200), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bcs_id'], ['board_class_subject.bcs_id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    op.add_column('book_details', sa.Column('board_id', sa.Integer(), nullable=True))
    op.add_column('book_details', sa.Column('book_level', sa.String(length=1), nullable=True))
    op.create_foreign_key(None, 'book_details', 'message_detail', ['board_id'], ['msg_id'])
    op.add_column('school_profile', sa.Column('school_session_start', sa.DateTime(), nullable=True))
    op.add_column('topic_tracker', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic_tracker', 'chapter_detail', ['chapter_id'], ['chapter_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_tracker', type_='foreignkey')
    op.drop_column('topic_tracker', 'chapter_id')
    op.drop_column('school_profile', 'school_session_start')
    op.drop_constraint(None, 'book_details', type_='foreignkey')
    op.drop_column('book_details', 'book_level')
    op.drop_column('book_details', 'board_id')
    op.drop_table('chapter_detail')
    op.drop_table('board_detail')
    op.drop_table('board_class_subject')
    op.drop_table('board_class')
    # ### end Alembic commands ###
