"""empty message

Revision ID: c0b56ec7761f
Revises: 57e42fe36052
Create Date: 2020-07-03 18:41:06.712122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b56ec7761f'
down_revision = '57e42fe36052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_transaction',
    sa.Column('comm_tran_id', sa.Integer(), nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comm_id'], ['communication_detail.comm_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('comm_tran_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_transaction')
    # ### end Alembic commands ###
