"""empty message

Revision ID: c19d5c149b6f
Revises: b362a53980a7
Create Date: 2019-06-11 20:11:59.891005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19d5c149b6f'
down_revision = 'b362a53980a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_section',
    sa.Column('class_sec_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('class_val', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=1), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('class_teacher', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_teacher'], ['teacher_profile.teacher_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.PrimaryKeyConstraint('class_sec_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_section')
    # ### end Alembic commands ###
