"""empty message

Revision ID: c270d0b9d089
Revises: 5e89df74da18
Create Date: 2019-06-11 19:49:41.258380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c270d0b9d089'
down_revision = '5e89df74da18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('txt', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
