"""empty message

Revision ID: c51643298800
Revises: beb5a5eb4501
Create Date: 2019-06-28 19:14:55.179046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51643298800'
down_revision = 'beb5a5eb4501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('response_option', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_capture', 'response_option')
    # ### end Alembic commands ###
