"""empty message

Revision ID: c8150ea46b76
Revises: fcd46ca30243
Create Date: 2019-12-06 17:52:26.134852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8150ea46b76'
down_revision = 'fcd46ca30243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_detail', sa.Column('test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_detail', 'test_details', ['test_id'], ['test_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_detail', type_='foreignkey')
    op.drop_column('session_detail', 'test_id')
    # ### end Alembic commands ###
