"""empty message

Revision ID: c885a4ea6a79
Revises: 846789698289
Create Date: 2020-04-14 13:25:53.536899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c885a4ea6a79'
down_revision = '846789698289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_class_subject_books', sa.Column('is_archieved', sa.String(length=1), nullable=True))
    op.drop_column('board_class_subject_books', 'is_archieve')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_class_subject_books', sa.Column('is_archieve', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.drop_column('board_class_subject_books', 'is_archieved')
    # ### end Alembic commands ###
