"""empty message

Revision ID: caa2573131be
Revises: 0ef9066ee29b
Create Date: 2019-11-05 00:28:36.639260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa2573131be'
down_revision = '0ef9066ee29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_detail', sa.Column('benefits', sa.String(length=200), nullable=True))
    op.add_column('job_detail', sa.Column('job_type', sa.String(length=50), nullable=True))
    op.add_column('school_profile', sa.Column('location_type', sa.String(length=50), nullable=True))
    op.add_column('school_profile', sa.Column('school_type', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('willing_to_travel', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'willing_to_travel')
    op.drop_column('school_profile', 'school_type')
    op.drop_column('school_profile', 'location_type')
    op.drop_column('job_detail', 'job_type')
    op.drop_column('job_detail', 'benefits')
    # ### end Alembic commands ###
