"""empty message

Revision ID: cc739b171d18
Revises: 
Create Date: 2020-07-18 15:39:54.054000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc739b171d18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_detail',
    sa.Column('fee_trans_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('fee_amount', sa.Integer(), nullable=True),
    sa.Column('fee_paid_amount', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('paid_status', sa.String(length=1), nullable=False),
    sa.Column('delay_reason', sa.String(length=100), nullable=True),
    sa.Column('outstanding_amount', sa.Integer(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('fee_trans_id')
    )
    op.drop_table('school_fee_mgt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_fee_mgt',
    sa.Column('fee_trans_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fee_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee_paid_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delay_reason', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outstanding_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('class_sec_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], name='school_fee_mgt_class_sec_id_fkey'),
    sa.ForeignKeyConstraint(['delay_reason'], ['message_detail.msg_id'], name='school_fee_mgt_delay_reason_fkey'),
    sa.ForeignKeyConstraint(['is_paid'], ['message_detail.msg_id'], name='school_fee_mgt_is_paid_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='school_fee_mgt_school_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name='school_fee_mgt_student_id_fkey'),
    sa.PrimaryKeyConstraint('fee_trans_id', name='school_fee_mgt_pkey')
    )
    op.drop_table('fee_detail')
    # ### end Alembic commands ###
