"""empty message

Revision ID: ce7f5306888f
Revises: 25c858a3ad15
Create Date: 2019-12-12 13:53:52.345771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7f5306888f'
down_revision = '25c858a3ad15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_profile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profile', type_='foreignkey')
    op.drop_column('student_profile', 'user_id')
    # ### end Alembic commands ###
