"""empty message

Revision ID: d160bb1d77cf
Revises: 
Create Date: 2019-06-18 13:09:24.659341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd160bb1d77cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_details', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_details', 'message_detail', ['class_id'], ['msg_id'])
    op.drop_column('book_details', 'book_link')
    op.drop_column('book_details', 'class_val')
    op.add_column('result_upload', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'result_upload', 'teacher_profile', ['uploaded_by'], ['teacher_id'])
    op.add_column('topic_detail', sa.Column('book_link', sa.String(length=500), nullable=True))
    op.drop_constraint('topic_detail_book_id_fkey', 'topic_detail', type_='foreignkey')
    op.drop_column('topic_detail', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_detail', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('topic_detail_book_id_fkey', 'topic_detail', 'book_details', ['book_id'], ['book_id'])
    op.drop_column('topic_detail', 'book_link')
    op.drop_constraint(None, 'result_upload', type_='foreignkey')
    op.drop_column('result_upload', 'uploaded_by')
    op.add_column('book_details', sa.Column('class_val', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('book_details', sa.Column('book_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book_details', type_='foreignkey')
    op.drop_column('book_details', 'class_id')
    # ### end Alembic commands ###
