"""empty message

Revision ID: d1647e936e9e
Revises: 6afc0e2f3a93
Create Date: 2019-06-20 13:21:47.472708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1647e936e9e'
down_revision = '6afc0e2f3a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('is_present', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'is_present')
    # ### end Alembic commands ###
