"""empty message

Revision ID: d21d72d54a5f
Revises: aec3076b3b76
Create Date: 2020-04-16 21:26:45.058244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21d72d54a5f'
down_revision = 'aec3076b3b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_survey_response', sa.Column('survey_response_id', sa.Integer(), nullable=False))
    op.drop_column('student_survey_response', 'survey_reponse_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_survey_response', sa.Column('survey_reponse_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('student_survey_response', 'survey_response_id')
    # ### end Alembic commands ###
