"""empty message

Revision ID: d25646a61d2e
Revises: 6a67dfee6b17
Create Date: 2020-07-28 13:58:14.907748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25646a61d2e'
down_revision = '6a67dfee6b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_detail', sa.Column('is_archived', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_detail', 'is_archived')
    # ### end Alembic commands ###
