"""empty message

Revision ID: d27500f15dfc
Revises: 
Create Date: 2020-05-03 00:37:50.972621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27500f15dfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_detail',
    sa.Column('inv_id', sa.Integer(), nullable=False),
    sa.Column('inv_name', sa.String(length=200), nullable=False),
    sa.Column('inv_description', sa.String(length=500), nullable=False),
    sa.Column('inv_category', sa.Integer(), nullable=False),
    sa.Column('total_stock', sa.Float(), nullable=False),
    sa.Column('stock_out', sa.Float(), nullable=False),
    sa.Column('item_rate', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('is_archived', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inv_category'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('inv_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_detail')
    # ### end Alembic commands ###
