"""empty message

Revision ID: d31038f2b686
Revises: 
Create Date: 2020-07-24 21:31:27.104664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31038f2b686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_class_sec_detail',
    sa.Column('fcs_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.Column('class_val', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=1), nullable=True),
    sa.Column('is_current', sa.String(length=1), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.PrimaryKeyConstraint('fcs_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_class_sec_detail')
    # ### end Alembic commands ###
