"""empty message

Revision ID: d6625d2b2eb9
Revises: e0928d0e49c0
Create Date: 2019-06-27 14:32:54.763934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6625d2b2eb9'
down_revision = 'e0928d0e49c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guardian_profile', 'phone')
    op.drop_column('student_profile', 'phone')
    op.drop_column('teacher_profile', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_profile', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_profile', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('guardian_profile', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
