"""empty message

Revision ID: d6e5fa7f39be
Revises: 6151dc4f9062
Create Date: 2019-09-13 00:08:26.010163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e5fa7f39be'
down_revision = '6151dc4f9062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resp_session_question',
    sa.Column('resp_quest_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_details.question_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], ),
    sa.PrimaryKeyConstraint('resp_quest_id')
    )
    op.create_table('session_detail',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('resp_session_id', sa.String(length=20), nullable=True),
    sa.Column('session_status', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_detail')
    op.drop_table('resp_session_question')
    # ### end Alembic commands ###
