"""empty message

Revision ID: d7506849832e
Revises: 2b5a1caadeb7
Create Date: 2019-10-19 13:08:37.713807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7506849832e'
down_revision = '2b5a1caadeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result_upload', sa.Column('answer_sheet_ref', sa.String(length=300), nullable=True))
    op.add_column('result_upload', sa.Column('question_paper_ref', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result_upload', 'question_paper_ref')
    op.drop_column('result_upload', 'answer_sheet_ref')
    # ### end Alembic commands ###
