"""empty message

Revision ID: d89013dd8d86
Revises: 1b6541f21abe
Create Date: 2019-11-03 13:17:15.464562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89013dd8d86'
down_revision = '1b6541f21abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_application_teacher_id_fkey', 'job_application', type_='foreignkey')
    op.drop_column('job_application', 'teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('job_application_teacher_id_fkey', 'job_application', 'teacher_profile', ['teacher_id'], ['teacher_id'])
    # ### end Alembic commands ###
