"""empty message

Revision ID: d8ffc5199b2f
Revises: a2ad06191b32
Create Date: 2020-06-07 01:16:16.141929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ffc5199b2f'
down_revision = 'a2ad06191b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_class',
    sa.Column('live_class_id', sa.Integer(), nullable=False),
    sa.Column('class_sec_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=30), nullable=False),
    sa.Column('end_time', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=100), nullable=True),
    sa.Column('conf_link', sa.String(length=200), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], ),
    sa.PrimaryKeyConstraint('live_class_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_class')
    # ### end Alembic commands ###
