"""empty message

Revision ID: dd1db09c23b6
Revises: ea4a5f7a3bdf
Create Date: 2020-08-19 18:12:07.597343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1db09c23b6'
down_revision = 'ea4a5f7a3bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transaction', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transaction', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
