"""empty message

Revision ID: deda469544ac
Revises: d160bb1d77cf
Create Date: 2019-06-18 13:23:12.805275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deda469544ac'
down_revision = 'd160bb1d77cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_details', sa.Column('book_link', sa.String(length=500), nullable=True))
    op.add_column('book_details', sa.Column('class_val', sa.Integer(), nullable=True))
    op.drop_constraint('book_details_class_id_fkey', 'book_details', type_='foreignkey')
    op.drop_column('book_details', 'class_id')
    op.add_column('topic_detail', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic_detail', 'book_details', ['book_id'], ['book_id'])
    op.drop_column('topic_detail', 'book_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_detail', sa.Column('book_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topic_detail', type_='foreignkey')
    op.drop_column('topic_detail', 'book_id')
    op.add_column('book_details', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_details_class_id_fkey', 'book_details', 'message_detail', ['class_id'], ['msg_id'])
    op.drop_column('book_details', 'class_val')
    op.drop_column('book_details', 'book_link')
    # ### end Alembic commands ###
