"""empty message

Revision ID: e0928d0e49c0
Revises: 30ac849bf430
Create Date: 2019-06-27 13:11:31.955302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0928d0e49c0'
down_revision = '30ac849bf430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_profile',
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('relation', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relation'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('guardian_id')
    )
    op.add_column('student_profile', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('student_profile', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('student_profile', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profile', 'phone')
    op.drop_column('student_profile', 'email')
    op.drop_column('student_profile', 'address')
    op.drop_table('guardian_profile')
    # ### end Alembic commands ###
