"""empty message

Revision ID: e1f6cac643af
Revises: 3ebb2ba02d0e
Create Date: 2019-06-14 19:39:42.114739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f6cac643af'
down_revision = '3ebb2ba02d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'message_detail', ['user_type'], ['msg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
