"""empty message

Revision ID: e2a6cf22eb07
Revises: 
Create Date: 2020-09-13 22:10:57.559056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a6cf22eb07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_certs',
    sa.Column('tc_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('school_adm_number', sa.String(length=120), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('tc_url', sa.String(length=200), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], ),
    sa.PrimaryKeyConstraint('tc_id')
    )
    op.add_column('response_capture', sa.Column('student_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'response_capture', 'user', ['student_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response_capture', type_='foreignkey')
    op.drop_column('response_capture', 'student_user_id')
    op.drop_table('transfer_certs')
    # ### end Alembic commands ###
