"""empty message

Revision ID: e2cab87dbcbc
Revises: 91f83f684510
Create Date: 2019-10-22 21:48:17.757915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cab87dbcbc'
down_revision = '91f83f684510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_detail', sa.Column('sub_duration_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_detail', 'sub_duration_months')
    # ### end Alembic commands ###
