"""empty message

Revision ID: e349a5d7b208
Revises: 
Create Date: 2020-07-02 21:16:03.039942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e349a5d7b208'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('is_archived', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profile', 'is_archived')
    # ### end Alembic commands ###
