"""empty message

Revision ID: e46a85870570
Revises: 68fe6273f17c
Create Date: 2019-09-26 12:58:40.790961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46a85870570'
down_revision = '68fe6273f17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_detail',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_name', sa.String(length=200), nullable=True),
    sa.Column('reference_link', sa.String(length=300), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('archive_status', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_detail')
    # ### end Alembic commands ###
