"""empty message

Revision ID: ea4d08ca3c5f
Revises: bddc01733cef
Create Date: 2020-08-14 13:20:02.074234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4d08ca3c5f'
down_revision = 'bddc01733cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_detail', sa.Column('course_status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_detail', 'message_detail', ['course_status'], ['msg_id'])
    op.add_column('course_topics', sa.Column('video_class_url', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_topics', 'video_class_url')
    op.drop_constraint(None, 'course_detail', type_='foreignkey')
    op.drop_column('course_detail', 'course_status')
    # ### end Alembic commands ###
