"""empty message

Revision ID: ed2ee4c9695b
Revises: 1b45d10686bf
Create Date: 2019-07-15 23:43:22.461338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2ee4c9695b'
down_revision = '1b45d10686bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_detail', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'performance_detail', 'message_detail', ['subject_id'], ['msg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performance_detail', type_='foreignkey')
    op.drop_column('performance_detail', 'subject_id')
    # ### end Alembic commands ###
