"""empty message

Revision ID: f28561bcba24
Revises: b888e9c61376
Create Date: 2019-06-29 14:29:04.010154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28561bcba24'
down_revision = 'b888e9c61376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_capture', 'resp_session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_capture', sa.Column('resp_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
