"""empty message

Revision ID: f2e1f8107ffa
Revises: f3bd04255981
Create Date: 2020-06-06 17:59:43.804126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e1f8107ffa'
down_revision = 'f3bd04255981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_class', sa.Column('chapter_num', sa.Integer(), nullable=True))
    op.add_column('live_class', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.add_column('live_class', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.drop_constraint('live_class_teacher_id_fkey', 'live_class', type_='foreignkey')
    op.create_foreign_key(None, 'live_class', 'message_detail', ['subject_id'], ['msg_id'])
    op.create_foreign_key(None, 'live_class', 'topic_detail', ['topic_id'], ['topic_id'])
    op.drop_column('live_class', 'book_chapter')
    op.drop_column('live_class', 'subject')
    op.drop_column('live_class', 'teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_class', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('live_class', sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('live_class', sa.Column('book_chapter', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'live_class', type_='foreignkey')
    op.drop_constraint(None, 'live_class', type_='foreignkey')
    op.create_foreign_key('live_class_teacher_id_fkey', 'live_class', 'user', ['teacher_id'], ['id'])
    op.drop_column('live_class', 'topic_id')
    op.drop_column('live_class', 'subject_id')
    op.drop_column('live_class', 'chapter_num')
    # ### end Alembic commands ###
