"""empty message

Revision ID: f3bd04255981
Revises: 
Create Date: 2020-06-06 17:36:36.739911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bd04255981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_class',
    sa.Column('live_class_id', sa.Integer(), nullable=False),
    sa.Column('class_val', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('book_chapter', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=30), nullable=False),
    sa.Column('end_time', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=100), nullable=True),
    sa.Column('class_link', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(length=100), nullable=True),
    sa.Column('is_archived', sa.String(length=1), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('live_class_id')
    )
    op.alter_column('board_class_subject', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('board_class_subject_board_det_id_fkey', 'board_class_subject', type_='foreignkey')
    op.drop_column('board_class_subject', 'board_det_id')
    op.add_column('homework_detail', sa.Column('attachment', sa.String(length=200), nullable=True))
    op.add_column('homework_questions', sa.Column('ref_type', sa.Integer(), nullable=True))
    op.add_column('homework_questions', sa.Column('ref_url', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'homework_questions', 'message_detail', ['ref_type'], ['msg_id'])
    op.add_column('student_homework_response', sa.Column('teacher_remark', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_homework_response', 'teacher_remark')
    op.drop_constraint(None, 'homework_questions', type_='foreignkey')
    op.drop_column('homework_questions', 'ref_url')
    op.drop_column('homework_questions', 'ref_type')
    op.drop_column('homework_detail', 'attachment')
    op.add_column('board_class_subject', sa.Column('board_det_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('board_class_subject_board_det_id_fkey', 'board_class_subject', 'board_detail', ['board_det_id'], ['board_det_id'])
    op.alter_column('board_class_subject', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('live_class')
    # ### end Alembic commands ###
