"""empty message

Revision ID: f7255be72641
Revises: 
Create Date: 2019-07-01 17:52:00.891581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7255be72641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_profile',
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('relation', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relation'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('guardian_id')
    )
    op.create_table('student_qr_options',
    sa.Column('student_qr_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(length=1), nullable=True),
    sa.Column('qr_link', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('student_qr_id')
    )
    op.create_table('topic_detail',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=True),
    sa.Column('class_val', sa.Integer(), nullable=True),
    sa.Column('unit_num', sa.Integer(), nullable=True),
    sa.Column('chapter_num', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book_details.book_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('topic_tracker',
    sa.Column('topic_track_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('class_sec_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('is_covered', sa.String(length=1), nullable=True),
    sa.Column('cover_Date', sa.DateTime(), nullable=True),
    sa.Column('next_topic', sa.Integer(), nullable=True),
    sa.Column('last_modified_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], ),
    sa.ForeignKeyConstraint(['next_topic'], ['topic_detail.topic_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_detail.topic_id'], ),
    sa.PrimaryKeyConstraint('topic_track_id')
    )
    op.drop_table('tbl_lookup')
    op.drop_table('content_tracker')
    op.drop_table('content')
    op.drop_table('tbl_Geography')
    op.alter_column('alllearn_school_perf', 'avg_perf_alllearn',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alllearn_school_perf', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('alllearn_school_perf', 'quarter',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alllearn_school_perf', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('book_details', sa.Column('book_link', sa.String(length=500), nullable=True))
    op.add_column('book_details', sa.Column('class_val', sa.Integer(), nullable=True))
    op.alter_column('book_details', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('book_details_class_id_fkey', 'book_details', type_='foreignkey')
    op.drop_column('book_details', 'class_id')
    op.alter_column('calendar', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('calendar', 'date_aging',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('calendar', 'month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'month_aging',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'month_name',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'semi_annual',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'semi_annual_aging',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'week_aging',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calendar', 'year_aging',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('class_section', sa.Column('class_val', sa.Integer(), nullable=True))
    op.add_column('class_section', sa.Column('section', sa.String(length=1), nullable=True))
    op.alter_column('class_section', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_section', 'student_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('class_section_section_id_fkey', 'class_section', type_='foreignkey')
    op.drop_constraint('class_section_class_id_fkey', 'class_section', type_='foreignkey')
    op.drop_column('class_section', 'section_id')
    op.drop_column('class_section', 'class_id')
    op.alter_column('event_detail', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event_detail', 'event_color',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event_detail', 'event_duration_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event_detail', 'event_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('event_detail', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_details', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('financial_details', 'maint_cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('financial_details', 'month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('financial_details', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('financial_details', 'subscription_amt',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('financial_details', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message_detail', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('performance_detail', 'class_avg_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'class_year_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('performance_detail', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('performance_detail', 'month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'school_avg_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'school_month_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'school_semi_annual_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'school_year_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'section_avg_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'section_semi_annual_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'section_year_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'semi_annual',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'student_month_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'student_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'student_semi_annual_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'student_year_rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('performance_detail', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('question_details', sa.Column('class_val', sa.Integer(), nullable=True))
    op.add_column('question_details', sa.Column('reference_link', sa.String(length=120), nullable=True))
    op.add_column('question_details', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.alter_column('question_details', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_details', 'question_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('question_details', 'question_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('question_details', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('question_details_class_id_fkey', 'question_details', type_='foreignkey')
    op.create_foreign_key(None, 'question_details', 'topic_detail', ['topic_id'], ['topic_id'])
    op.drop_column('question_details', 'slideshow_id')
    op.drop_column('question_details', 'class_id')
    op.drop_column('question_details', 'references')
    op.add_column('question_options', sa.Column('option', sa.String(length=1), nullable=True))
    op.alter_column('question_options', 'is_correct',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_options', 'option_desc',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('question_options', 'option_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_options', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recomm_detail', 'if_this',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('recomm_detail', 'subject',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recomm_detail', 'then_this',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.add_column('response_capture', sa.Column('resp_session_id', sa.String(length=20), nullable=True))
    op.alter_column('response_capture', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('response_capture', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('response_capture', 'response_option',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('response_capture', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('response_capture', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('response_capture', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('response_capture', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('response_capture_response_option_fkey', 'response_capture', type_='foreignkey')
    op.drop_column('response_capture', 'slideshow_id')
    op.add_column('result_upload', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.alter_column('result_upload', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result_upload', 'is_present',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result_upload', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result_upload', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result_upload', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result_upload', 'test_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result_upload', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'result_upload', 'teacher_profile', ['uploaded_by'], ['teacher_id'])
    op.alter_column('school_fee_mgt', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'delay_reason',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'fee_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'fee_paid_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'is_paid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'outstanding_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_fee_mgt', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_profile', 'city',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school_profile', 'registered_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('school_profile', 'school_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('school_profile', 'state',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('search', 'is_error_page',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('search', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('search', 'redirect_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('search', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('search', 'search_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('search', 'search_keywords',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('student_profile', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('student_profile', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('student_profile', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('student_profile', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('student_profile', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('student_profile', sa.Column('phone', sa.String(length=12), nullable=True))
    op.alter_column('student_profile', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_profile', 'dob',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('student_profile', 'gender',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_profile', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('student_profile', 'student_name')
    op.alter_column('survivor_details', 'sur_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('survivor_details', 'sur_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('teacher_profile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('teacher_profile', 'designation',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_profile', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teacher_profile', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_profile', 'profile_picture',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('teacher_profile', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('teacher_profile', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teacher_profile', 'school_leaving_reason',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('teacher_profile', 'teacher_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_foreign_key(None, 'teacher_profile', 'user', ['user_id'], ['id'])
    op.alter_column('test_details', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_details', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_details', 'test_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('test_questions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_questions', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('user_avatar', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'message_detail', ['user_type'], ['msg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'user_avatar')
    op.alter_column('test_questions', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_questions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_details', 'test_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('test_details', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_details', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'teacher_profile', type_='foreignkey')
    op.alter_column('teacher_profile', 'teacher_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('teacher_profile', 'school_leaving_reason',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('teacher_profile', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teacher_profile', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('teacher_profile', 'profile_picture',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('teacher_profile', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teacher_profile', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teacher_profile', 'designation',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('teacher_profile', 'user_id')
    op.alter_column('survivor_details', 'sur_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('survivor_details', 'sur_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('student_profile', sa.Column('student_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.alter_column('student_profile', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_profile', 'gender',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_profile', 'dob',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('student_profile', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('student_profile', 'phone')
    op.drop_column('student_profile', 'last_name')
    op.drop_column('student_profile', 'full_name')
    op.drop_column('student_profile', 'first_name')
    op.drop_column('student_profile', 'email')
    op.drop_column('student_profile', 'address')
    op.alter_column('search', 'search_keywords',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('search', 'search_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('search', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('search', 'redirect_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('search', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('search', 'is_error_page',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_profile', 'state',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_profile', 'school_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('school_profile', 'registered_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('school_profile', 'city',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'outstanding_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'is_paid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'fee_paid_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'fee_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'delay_reason',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school_fee_mgt', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'result_upload', type_='foreignkey')
    op.alter_column('result_upload', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result_upload', 'test_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result_upload', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result_upload', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result_upload', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result_upload', 'is_present',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result_upload', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('result_upload', 'uploaded_by')
    op.add_column('response_capture', sa.Column('slideshow_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('response_capture_response_option_fkey', 'response_capture', 'question_options', ['response_option'], ['option_id'])
    op.alter_column('response_capture', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_capture', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_capture', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_capture', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_capture', 'response_option',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_capture', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response_capture', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('response_capture', 'resp_session_id')
    op.alter_column('recomm_detail', 'then_this',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('recomm_detail', 'subject',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recomm_detail', 'if_this',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('question_options', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_options', 'option_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_options', 'option_desc',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('question_options', 'is_correct',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('question_options', 'option')
    op.add_column('question_details', sa.Column('references', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('question_details', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('question_details', sa.Column('slideshow_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question_details', type_='foreignkey')
    op.create_foreign_key('question_details_class_id_fkey', 'question_details', 'message_detail', ['class_id'], ['msg_id'])
    op.alter_column('question_details', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_details', 'question_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('question_details', 'question_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('question_details', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('question_details', 'topic_id')
    op.drop_column('question_details', 'reference_link')
    op.drop_column('question_details', 'class_val')
    op.alter_column('performance_detail', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'student_year_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'student_semi_annual_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'student_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'student_month_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'semi_annual',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'section_year_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'section_semi_annual_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'section_avg_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'school_year_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'school_semi_annual_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'school_month_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'school_avg_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('performance_detail', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('performance_detail', 'class_year_rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_detail', 'class_avg_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message_detail', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('financial_details', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('financial_details', 'subscription_amt',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('financial_details', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('financial_details', 'month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('financial_details', 'maint_cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('financial_details', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event_detail', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event_detail', 'event_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('event_detail', 'event_duration_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event_detail', 'event_color',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event_detail', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('class_section', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('class_section', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('class_section_class_id_fkey', 'class_section', 'message_detail', ['class_id'], ['msg_id'])
    op.create_foreign_key('class_section_section_id_fkey', 'class_section', 'message_detail', ['section_id'], ['msg_id'])
    op.alter_column('class_section', 'student_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('class_section', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('class_section', 'section')
    op.drop_column('class_section', 'class_val')
    op.alter_column('calendar', 'year_aging',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'week_aging',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'semi_annual_aging',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'semi_annual',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'month_name',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'month_aging',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('calendar', 'date_aging',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('calendar', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('book_details', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('book_details_class_id_fkey', 'book_details', 'message_detail', ['class_id'], ['msg_id'])
    op.alter_column('book_details', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('book_details', 'class_val')
    op.drop_column('book_details', 'book_link')
    op.alter_column('attendance', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'class_sec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('alllearn_school_perf', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('alllearn_school_perf', 'quarter',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('alllearn_school_perf', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('alllearn_school_perf', 'avg_perf_alllearn',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('tbl_Geography',
    sa.Column('GEO_ID', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('COUNTRY', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('STATE', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('CITY', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('GEO_ID', name='tbl_Geography_pkey')
    )
    op.create_table('content',
    sa.Column('content_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['message_detail.msg_id'], name='content_board_id_fkey'),
    sa.ForeignKeyConstraint(['chapter_id'], ['message_detail.msg_id'], name='content_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['class_id'], ['message_detail.msg_id'], name='content_class_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], name='content_subject_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['message_detail.msg_id'], name='content_topic_id_fkey'),
    sa.PrimaryKeyConstraint('content_id', name='content_pkey')
    )
    op.create_table('content_tracker',
    sa.Column('cont_track_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_sec_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_modified_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_sec_id'], ['class_section.class_sec_id'], name='content_tracker_class_sec_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['school_profile.school_id'], name='content_tracker_school_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['message_detail.msg_id'], name='content_tracker_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profile.teacher_id'], name='content_tracker_teacher_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['message_detail.msg_id'], name='content_tracker_topic_id_fkey'),
    sa.PrimaryKeyConstraint('cont_track_id', name='content_tracker_pkey')
    )
    op.create_table('tbl_lookup',
    sa.Column('ID', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('CATEGORY', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DESCRIPTION', sa.VARCHAR(length=200), autoincrement=False, nullable=True)
    )
    op.drop_table('topic_tracker')
    op.drop_table('topic_detail')
    op.drop_table('student_qr_options')
    op.drop_table('guardian_profile')
    # ### end Alembic commands ###
