"""empty message

Revision ID: f859135f02d4
Revises: 8051700f5986
Create Date: 2020-08-19 14:57:40.636059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f859135f02d4'
down_revision = '8051700f5986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_batch', sa.Column('course_batch_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_batch', 'course_batch_fee')
    # ### end Alembic commands ###
