"""empty message

Revision ID: fa4fa5541921
Revises: 971143e523d1
Create Date: 2020-06-21 12:02:51.492420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4fa5541921'
down_revision = '971143e523d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_class', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('live_class', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_class', 'start_time')
    op.drop_column('live_class', 'end_time')
    # ### end Alembic commands ###
