"""empty message

Revision ID: fcb4f3a3875c
Revises: 289e5b3a3b04
Create Date: 2020-07-04 19:50:11.708385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb4f3a3875c'
down_revision = '289e5b3a3b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_transaction',
    sa.Column('comm_tran_id', sa.Integer(), nullable=False),
    sa.Column('comm_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comm_id'], ['communication_detail.comm_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], ),
    sa.PrimaryKeyConstraint('comm_tran_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_transaction')
    # ### end Alembic commands ###
