"""empty message

Revision ID: fcd46ca30243
Revises: 73b08f202a05
Create Date: 2019-11-06 17:40:17.647291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd46ca30243'
down_revision = '73b08f202a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_detail', sa.Column('city', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_detail', 'city')
    # ### end Alembic commands ###
